### ISSUE TITLE
Entity state exception

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#11]
Spigot 1.11.2 latest, Plan 2.5.1. Log reports every minute:

> [13:24:02 WARN]: [Plan] Plugin Plan v2.5.1 generated an exception while executing task 158
java.lang.IllegalStateException: Asynchronous entity track!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot-1.11.2.jar-2017-02-11-0122:git-Spigot-65a0347-a552117]
        at net.minecraft.server.v1_11_R1.EntityTracker.addEntity(EntityTracker.java:108) ~[spigot-1.11.2.jar-2017-02-11-0122:git-Spigot-65a0347-a552117]
        at net.minecraft.server.v1_11_R1.EntityTracker.track(EntityTracker.java:88) ~[spigot-1.11.2.jar-2017-02-11-0122:git-Spigot-65a0347-a552117]
        at net.minecraft.server.v1_11_R1.WorldManager.a(WorldManager.java:21) ~[spigot-1.11.2.jar-2017-02-11-0122:git-Spigot-65a0347-a552117]
        at net.minecraft.server.v1_11_R1.World.b(World.java:1089) ~[spigot-1.11.2.jar-2017-02-11-0122:git-Spigot-65a0347-a552117]
        at net.minecraft.server.v1_11_R1.WorldServer.b(WorldServer.java:1113) ~[spigot-1.11.2.jar-2017-02-11-0122:git-Spigot-65a0347-a552117]
        at net.minecraft.server.v1_11_R1.WorldServer.a(WorldServer.java:1078) ~[spigot-1.11.2.jar-2017-02-11-0122:git-Spigot-65a0347-a552117]
        at net.minecraft.server.v1_11_R1.Chunk.addEntities(Chunk.java:753) ~[spigot-1.11.2.jar-2017-02-11-0122:git-Spigot-65a0347-a552117]
        at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45) ~[spigot-1.11.2.jar-2017-02-11-0122:git-Spigot-65a0347-a552117]
        at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) ~[spigot-1.11.2.jar-2017-02-11-0122:git-Spigot-65a0347-a552117]
        at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) ~[spigot-1.11.2.jar-2017-02-11-0122:git-Spigot-65a0347-a552117]
        at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[spigot-1.11.2.jar-2017-02-11-0122:git-Spigot-65a0347-a552117]
        at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[spigot-1.11.2.jar-2017-02-11-0122:git-Spigot-65a0347-a552117]
        at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137) ~[spigot-1.11.2.jar-2017-02-11-0122:git-Spigot-65a0347-a552117]
        at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) ~[spigot-1.11.2.jar-2017-02-11-0122:git-Spigot-65a0347-a552117]
        at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[spigot-1.11.2.jar-2017-02-11-0122:git-Spigot-65a0347-a552117]
        at net.minecraft.server.v1_11_R1.World.getChunkAt(World.java:329) ~[spigot-1.11.2.jar-2017-02-11-0122:git-Spigot-65a0347-a552117]
        at net.minecraft.server.v1_11_R1.World.getChunkAtWorldCoords(World.java:325) ~[spigot-1.11.2.jar-2017-02-11-0122:git-Spigot-65a0347-a552117]
        at net.minecraft.server.v1_11_R1.World.getType(World.java:806) ~[spigot-1.11.2.jar-2017-02-11-0122:git-Spigot-65a0347-a552117]
        at net.minecraft.server.v1_11_R1.EntityHuman.getBed(EntityHuman.java:1355) ~[spigot-1.11.2.jar-2017-02-11-0122:git-Spigot-65a0347-a552117]
        at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.getBedSpawnLocation(CraftPlayer.java:883) ~[spigot-1.11.2.jar-2017-02-11-0122:git-Spigot-65a0347-a552117]
        at com.djrapitops.plan.data.UserData.<init>(UserData.java:80) ~[?:?]
        at com.djrapitops.plan.database.databases.SQLDB.getUserData(SQLDB.java:554) ~[?:?]
        at com.djrapitops.plan.data.cache.DataCacheHandler.getCurrentData(DataCacheHandler.java:132) ~[?:?]
        at com.djrapitops.plan.data.cache.DataCacheHandler.getCurrentData(DataCacheHandler.java:164) ~[?:?]
        at com.djrapitops.plan.data.cache.DataCacheHandler.saveHandlerDataToCache(DataCacheHandler.java:247) ~[?:?]
        at com.djrapitops.plan.data.cache.DataCacheHandler.lambda$saveHandlerDataToCache$0(DataCacheHandler.java:227) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_121]
        at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_121]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_121]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_121]
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[?:1.8.0_121]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_121]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_121]
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401) ~[?:1.8.0_121]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) ~[?:1.8.0_121]
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) ~[?:1.8.0_121]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) ~[?:1.8.0_121]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:1.8.0_121]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_121]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583) ~[?:1.8.0_121]
        at com.djrapitops.plan.data.cache.DataCacheHandler.saveHandlerDataToCache(DataCacheHandler.java:226) ~[?:?]
        at com.djrapitops.plan.data.cache.DataCacheHandler.access$000(DataCacheHandler.java:27) ~[?:?]
        at com.djrapitops.plan.data.cache.DataCacheHandler$1.run(DataCacheHandler.java:95) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar-2017-02-11-0122:git-Spigot-65a0347-a552117]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.11.2.jar-2017-02-11-0122:git-Spigot-65a0347-a552117]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

It seemed to be related to my (player) location. When I moved, the errors stopped.

**Comment by SlimeDog** [comment]
This issue may be related to a Citizens entity of type PLAYER. Not a real player, but maybe Plan is confused?

**Comment by Rsl1122** [comment]
Nah, it's a bug caused because I'm using Bukkit API during async event, when that is not supposed to be done - I'll just disable bedlocation all together in the next version since it is not even visible or meaningful.
I'll upload a bugfix to this today.

**Comment by Rsl1122** [comment]
Fixed in 2.5.2.
