### ISSUE TITLE
[bug] /plan reload throws error.

### ISSUE THREAD

**Issue by FrozenBeard** [Rsl1122/Plan-PlayerAnalytics#120]
I updated my config to include the export feature, enabled this, disabled the web server and did /plan reload. It threw this error. Not sure if its vital or not!

```
[13:23:05] [Server thread/INFO]: [Plan] Shutting down Webserver..
[13:23:05] [Server thread/WARN]: Unexpected exception while parsing console command "plan reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'plan' in plugin Plan v3.4.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:675) ~[patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:638) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:441) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [patched_1.11.2.jar:git-Paper-1104]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at main.java.com.djrapitops.plan.ui.webserver.WebSocketServer.stop(WebSocketServer.java:102) ~[?:?]
	at main.java.com.djrapitops.plan.Plan.onDisable(Plan.java:151) ~[?:?]
	at main.java.com.djrapitops.plan.command.commands.ReloadCommand.onCommand(ReloadCommand.java:35) ~[?:?]
	at main.java.com.djrapitops.plan.command.PlanCommand.onCommand(PlanCommand.java:128) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.11.2.jar:git-Paper-1104]
	... 8 more
```

**Comment by Rsl1122** [comment]
If it doesn't throw it when the plugin is disabled next time it is likely something related to the new config settings being used while disabling the plugin - I'll fix that in the next update, should be out sometime tomorrow if nothing severe comes up.
