### ISSUE TITLE
Hook error

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#17]
Spigot 1.11.2 latest, Plan 2.6.0

> [12:34:19] [Server thread/INFO]: [Plan] Enabling Plan v2.6.0
[12:34:19] [Server thread/INFO]: [Plan] Using locale: Default: EN
[12:34:19] [Server thread/INFO]: [Plan] You're running the latest version
[12:34:19] [Server thread/INFO]: [Plan] Database init..
[12:34:19] [Server thread/INFO]: [Plan] sqlite-database connection established.
[12:34:20] [Server thread/INFO]: [Plan] Initializing Webserver..
[12:34:20] [Server thread/INFO]: [Plan] Webserver running on PORT 8804
[12:34:20] [Server thread/INFO]: [Plan] Analysis | Boot analysis in 30 seconds..
[12:34:20] [Server thread/ERROR]: Error occurred while enabling Plan v2.6.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/palmergames/bukkit/towny/exceptions/NotRegisteredException
        at main.java.com.djrapitops.plan.data.additional.HookHandler.hook(HookHandler.java:39) ~[?:?]
        at main.java.com.djrapitops.plan.data.additional.HookHandler.<init>(HookHandler.java:27) ~[?:?]
        at main.java.com.djrapitops.plan.Plan.onEnable(Plan.java:147) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2.jar-2017-02-21-0949:git-Spigot-d4f98a3-cb61ac0]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar-2017-02-21-0949:git-Spigot-d4f98a3-cb61ac0]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar-2017-02-21-0949:git-Spigot-d4f98a3-cb61ac0]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2.jar-2017-02-21-0949:git-Spigot-d4f98a3-cb61ac0]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2.jar-2017-02-21-0949:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.11.2.jar-2017-02-21-0949:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.11.2.jar-2017-02-21-0949:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.11.2.jar-2017-02-21-0949:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar-2017-02-21-0949:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.11.2.jar-2017-02-21-0949:git-Spigot-d4f98a3-cb61ac0]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: com.palmergames.bukkit.towny.exceptions.NotRegisteredException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.11.2.jar-2017-02-21-0949:git-Spigot-d4f98a3-cb61ac0]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.11.2.jar-2017-02-21-0949:git-Spigot-d4f98a3-cb61ac0]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
        ... 14 more

**Comment by SlimeDog** [comment]
and every 5 minutes

> [12:34:59] [Server thread/INFO]: [Plan] Analysis | Starting Boot Analysis..
[12:34:59] [Craft Scheduler Thread - 23/ERROR]: [Plan] Ran into an error. It has been logged to the Errors.txt
[12:34:59] [Craft Scheduler Thread - 3/ERROR]: [Plan] Ran into an error. It has been logged to the Errors.txt
[12:36:13] [Server thread/INFO]: ^[[0;32;1mPerWorldInventory^[[0;37;1m version ^[[0;32;1m1.9.2^[[m
[12:36:13] [Server thread/INFO]: Author: ^[[0;32;1mGnat008^[[m
[12:39:30] [Craft Scheduler Thread - 28/ERROR]: [Plan] Ran into an error. It has been logged to the Errors.txt
[12:39:30] [Craft Scheduler Thread - 27/ERROR]: [Plan] Ran into an error. It has been logged to the Errors.txt

Errors.txt

> 

> [Feb 21 12:39:30] main.java.com.djrapitops.plan.data.cache.DataCacheHandler$2 Caught java.sql.SQLException: no such column: 'current_nick'
[Feb 21 12:39:30]   org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:48)
[Feb 21 12:39:30]   org.sqlite.jdbc3.JDBC3ResultSet.getBoolean(JDBC3ResultSet.java:218)
[Feb 21 12:39:30]   main.java.com.djrapitops.plan.database.databases.SQLDB.getNicknames(SQLDB.java:636)
[Feb 21 12:39:30]   main.java.com.djrapitops.plan.database.databases.SQLDB.giveUserDataToProcessors(SQLDB.java:549)
[Feb 21 12:39:30]   main.java.com.djrapitops.plan.data.cache.DataCacheHandler$2.run(DataCacheHandler.java:132)
[Feb 21 12:39:30]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[Feb 21 12:39:30]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[Feb 21 12:39:30]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[Feb 21 12:39:30]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[Feb 21 12:39:30]   java.lang.Thread.run(Thread.java:745)
[Feb 21 12:39:30]  
[Feb 21 12:39:30] main.java.com.djrapitops.plan.data.cache.DataCacheHandler$2 Caught java.sql.SQLException: no such column: 'current_nick'
[Feb 21 12:39:30]   org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:48)
[Feb 21 12:39:30]   org.sqlite.jdbc3.JDBC3ResultSet.getBoolean(JDBC3ResultSet.java:218)
[Feb 21 12:39:30]   main.java.com.djrapitops.plan.database.databases.SQLDB.getNicknames(SQLDB.java:636)
[Feb 21 12:39:30]   main.java.com.djrapitops.plan.database.databases.SQLDB.giveUserDataToProcessors(SQLDB.java:549)
[Feb 21 12:39:30]   main.java.com.djrapitops.plan.data.cache.DataCacheHandler$2.run(DataCacheHandler.java:132)
[Feb 21 12:39:30]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[Feb 21 12:39:30]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[Feb 21 12:39:30]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[Feb 21 12:39:30]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[Feb 21 12:39:30]   java.lang.Thread.run(Thread.java:745)

**Comment by SlimeDog** [comment]
With SECOND Plan 2.6.0:

> [12:52:15] [Craft Scheduler Thread - 11/ERROR]: [Plan] Ran into an error. It has been logged to the Errors.txt
[12:52:15] [Craft Scheduler Thread - 5/ERROR]: [Plan] Ran into an error. It has been logged to the Errors.txt

Errors.txt
> [Feb 21 12:52:15] main.java.com.djrapitops.plan.data.cache.DataCacheHandler$2 Caught java.sql.SQLException: no such column: 'current_nick'
[Feb 21 12:52:15]   org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:48)
[Feb 21 12:52:15]   org.sqlite.jdbc3.JDBC3ResultSet.getBoolean(JDBC3ResultSet.java:218)
[Feb 21 12:52:15]   main.java.com.djrapitops.plan.database.databases.SQLDB.getNicknames(SQLDB.java:636)
[Feb 21 12:52:15]   main.java.com.djrapitops.plan.database.databases.SQLDB.giveUserDataToProcessors(SQLDB.java:549)
[Feb 21 12:52:15]   main.java.com.djrapitops.plan.data.cache.DataCacheHandler$2.run(DataCacheHandler.java:132)
[Feb 21 12:52:15]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[Feb 21 12:52:15]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[Feb 21 12:52:15]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[Feb 21 12:52:15]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[Feb 21 12:52:15]   java.lang.Thread.run(Thread.java:745)
[Feb 21 12:52:15] 
[Feb 21 12:52:15] main.java.com.djrapitops.plan.data.cache.DataCacheHandler$2 Caught java.sql.SQLException: no such column: 'current_nick'
[Feb 21 12:52:15]   org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:48)
[Feb 21 12:52:15]   org.sqlite.jdbc3.JDBC3ResultSet.getBoolean(JDBC3ResultSet.java:218)
[Feb 21 12:52:15]   main.java.com.djrapitops.plan.database.databases.SQLDB.getNicknames(SQLDB.java:636)
[Feb 21 12:52:15]   main.java.com.djrapitops.plan.database.databases.SQLDB.giveUserDataToProcessors(SQLDB.java:549)
[Feb 21 12:52:15]   main.java.com.djrapitops.plan.data.cache.DataCacheHandler$2.run(DataCacheHandler.java:132)
[Feb 21 12:52:15]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[Feb 21 12:52:15]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[Feb 21 12:52:15]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[Feb 21 12:52:15]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[Feb 21 12:52:15]   java.lang.Thread.run(Thread.java:745)

**Comment by SlimeDog** [comment]
Deleted the database, rebooted (so, no data). No errors until attempt to refresh web page.

> [Feb 21 13:56:47] main.java.com.djrapitops.plan.ui.webserver.Response Caught java.lang.NullPointerException
[Feb 21 13:56:47]   main.java.com.djrapitops.plan.data.additional.HookHandler.getAdditionalAnalysisReplaceRules(HookHandler.java:74)
[Feb 21 13:56:47]   main.java.com.djrapitops.plan.utilities.PlaceholderUtils.getAnalysisReplaceRules(PlaceholderUtils.java:64)
[Feb 21 13:56:47]   main.java.com.djrapitops.plan.ui.DataRequestHandler.getAnalysisHtml(DataRequestHandler.java:77)
[Feb 21 13:56:47]   main.java.com.djrapitops.plan.ui.webserver.Response.sendStaticResource(Response.java:103)
[Feb 21 13:56:47]   main.java.com.djrapitops.plan.ui.webserver.WebSocketServer$1.run(WebSocketServer.java:77)
[Feb 21 13:56:47]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[Feb 21 13:56:47]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[Feb 21 13:56:47]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[Feb 21 13:56:47]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[Feb 21 13:56:47]   java.lang.Thread.run(Thread.java:745)
