### ISSUE TITLE
Some versions of servers do not have google guava 10

### ISSUE THREAD

**Issue by Rsl1122** [Rsl1122/Plan-PlayerAnalytics#211]
**Server:** Cauldron 1.7.10
**Plan version:** 3.6.0

**Description:**
Causes Data not to be saved & Webserver to not serve pages.

**Console/Errors.txt/DebugLog.txt contents:**
```
org.apache.commons.lang.UnhandledException: Plugin Plan v3.6.0 generated an exception while executing task 51
    at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: guava10.com.google.common.cache.CacheBuilder.maximumSize(J)Lguava10/com/google/common/cache/CacheBuilder;
    at main.java.com.djrapitops.plan.data.cache.GeolocationCacheHandler.<clinit>(GeolocationCacheHandler.java:34)
    at main.java.com.djrapitops.plan.data.handling.LoginHandling.updateGeolocation(LoginHandling.java:54)
    at main.java.com.djrapitops.plan.data.handling.LoginHandling.processLoginInfo(LoginHandling.java:41)
    at main.java.com.djrapitops.plan.data.handling.info.LoginInfo.process(LoginInfo.java:69)
    at main.java.com.djrapitops.plan.data.listeners.PlanPlayerListener$1.run(PlanPlayerListener.java:85)
    at com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:37)
    at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more
```
```
Caused by: java.lang.NoSuchMethodError: guava10.com.google.common.cache.CacheBuilder.maximumSize(J)Lguava10/com/google/common/cache/CacheBuilder;
    at main.java.com.djrapitops.plan.data.cache.GeolocationCacheHandler.<clinit>(GeolocationCacheHandler.java:34)
    at main.java.com.djrapitops.plan.data.handling.LoginHandling.updateGeolocation(LoginHandling.java:54)
    at main.java.com.djrapitops.plan.data.handling.LoginHandling.processLoginInfo(LoginHandling.java:41)
    at main.java.com.djrapitops.plan.data.handling.info.LoginInfo.process(LoginInfo.java:69)
    at main.java.com.djrapitops.plan.data.listeners.PlanPlayerListener$1.run(PlanPlayerListener.java:85)
    at com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:37)
    at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more
```

**Comment by Fuzzlemann** [comment]
Can be fixed by removing .maximumSize(), just not sure if it's worth it.
