### ISSUE TITLE
1.7.X doesn't have correct Guava version for Plan

### ISSUE THREAD

**Issue by Rsl1122** [Rsl1122/Plan-PlayerAnalytics#218]
**Plan Version:** 3.6.1-DEV 6ddd7a212c293fe90a11e9be6ae3c5ad0e086178
**Server Version:** CraftBukkit 1.7.10
**Database Type:** sqlite

**Issue Caused by:** Old version of Guava

----

**Steps to Reproduce:**

1. Use Server 1.7.10

First Exception:
2. Join to the server

Second exception:
2. Wait for auto analysis

**Proposed Solution:**
Drop support for 1.7.X servers

----

**Console/Errors.txt/DebugLog.txt contents:**
```
[09:46:42 WARN]: org.apache.commons.lang.UnhandledException: Plugin Plan v3.6.0 generated an exception while executing task 5
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.build()Lcom/google/common/cache/Cache;
        at main.java.com.djrapitops.plan.data.cache.GeolocationCacheHandler.<clinit>(GeolocationCacheHandler.java:34)
        at main.java.com.djrapitops.plan.data.handling.LoginHandling.updateGeolocation(LoginHandling.java:54)
        at main.java.com.djrapitops.plan.data.handling.LoginHandling.processLoginInfo(LoginHandling.java:41)
        at main.java.com.djrapitops.plan.data.handling.info.LoginInfo.process(LoginInfo.java:69)
        at main.java.com.djrapitops.plan.data.cache.queue.ProcessConsumer.lambda$consume$0(DataCacheProcessQueue.java:93)
        at main.java.com.djrapitops.plan.database.databases.SQLDB.lambda$giveUserDataToProcessors$0(SQLDB.java:356)
        at java.util.Arrays$ArrayList.forEach(Unknown Source)
        at main.java.com.djrapitops.plan.database.databases.SQLDB.giveUserDataToProcessors(SQLDB.java:356)
        at main.java.com.djrapitops.plan.data.cache.queue.GetConsumer.consume(DataCacheGetQueue.java:85)
        at main.java.com.djrapitops.plan.data.cache.queue.GetConsumer.consume(DataCacheGetQueue.java:57)
        at main.java.com.djrapitops.plan.data.cache.queue.Consumer.run(Consumer.java:35)
        at com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:37)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:53)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```
```
[09:45:29 WARN]: org.apache.commons.lang.UnhandledException: Plugin Plan v3.6.0 generated an exception while executing task 16
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.build()Lcom/google/common/cache/Cache;
        at main.java.com.djrapitops.plan.data.cache.PageCacheHandler.<clinit>(PageCacheHandler.java:29)
        at main.java.com.djrapitops.plan.utilities.analysis.Analysis.analyzeData(Analysis.java:164)
        at main.java.com.djrapitops.plan.utilities.analysis.Analysis.analyze(Analysis.java:112)
        at main.java.com.djrapitops.plan.utilities.analysis.Analysis$1.run(Analysis.java:70)
        at com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:37)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:53)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```
----

Instructions for reporting timeout issues:

- Enable file debug mode by changing config setting "Debug" to "file"
- Reload the plugin
- Run the command that causes the timeout message to show
- Copy the contents of DebugLog.txt inside the code brackets above

**Comment by spannerman79** [comment]
1.7.10 uses guava 10.0.1

**Comment by spannerman79** [comment]
Reference: https://github.com/CyberdyneCC/Thermos-Bukkit/blob/ad9519650b6c3a0cf346b9a78d783221e62d99f9/pom.xml#L119..L121
```
<dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>10.0.1</version>
            <type>jar</type>
            <scope>compile</scope>
</dependency>
```

**Comment by Rsl1122** [comment]
Confirmed fixed
