### ISSUE TITLE
Errors with Export - Linux

### ISSUE THREAD

**Issue by Louis-D** [Rsl1122/Plan-PlayerAnalytics#235]
**Description of the issue**
Lots of errors in the console you already responded to me on the spigot forums.
https://hastebin.com/ayofubebis.vbs
https://hastebin.com/ejoxapolek.hs

**Hastebin link**
Link: https://hastebin.com/ovigagetar

**Comment by Rsl1122** [comment]
Does the mc server have write access at
`/data/website/`?

**Comment by Louis-D** [comment]
https://gyazo.com/b3a8709c8cff032af907dc561692b316
https://gyazo.com/03ec15aa5b3d3dd625eb215fb0750e8e
https://gyazo.com/e40a3f34f2bce6f27807434ecbe4631b
https://gyazo.com/aa8a0a715ba17c2c2dceead7ca71802e

**Comment by Fuzzlemann** [comment]
Happens when the path is absolute. Only tested with Linux.

Due to the error reported in #237 the StackTrace isn't available for me in the Errors.txt
The Error printed using e.printStackTrace():
`[22:31:04] [Craft Scheduler Thread - 10799/WARN]: java.io.IOException: No such file or directory
[22:31:04] [Craft Scheduler Thread - 10799/WARN]: 	at java.io.UnixFileSystem.createFileExclusively(Native Method)
[22:31:04] [Craft Scheduler Thread - 10799/WARN]: 	at java.io.File.createNewFile(File.java:1012)
[22:31:04] [Craft Scheduler Thread - 10799/WARN]: 	at main.java.com.djrapitops.plan.utilities.analysis.ExportUtility.writeInspectHtml(ExportUtility.java:127)
[22:31:04] [Craft Scheduler Thread - 10799/WARN]: 	at main.java.com.djrapitops.plan.data.cache.InspectCacheHandler.lambda$cache$1(InspectCacheHandler.java:54)
[22:31:04] [Craft Scheduler Thread - 10799/WARN]: 	at main.java.com.djrapitops.plan.database.databases.SQLDB.lambda$giveUserDataToProcessors$0(SQLDB.java:373)
[22:31:04] [Craft Scheduler Thread - 10799/WARN]: 	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
[22:31:04] [Craft Scheduler Thread - 10799/WARN]: 	at main.java.com.djrapitops.plan.database.databases.SQLDB.giveUserDataToProcessors(SQLDB.java:373)
[22:31:04] [Craft Scheduler Thread - 10799/WARN]: 	at main.java.com.djrapitops.plan.data.cache.queue.GetConsumer.consume(DataCacheGetQueue.java:86)
[22:31:04] [Craft Scheduler Thread - 10799/WARN]: 	at main.java.com.djrapitops.plan.data.cache.queue.GetConsumer.consume(DataCacheGetQueue.java:58)
[22:31:04] [Craft Scheduler Thread - 10799/WARN]: 	at main.java.com.djrapitops.plan.data.cache.queue.Consumer.run(Consumer.java:35)
[22:31:04] [Craft Scheduler Thread - 10799/WARN]: 	at com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:37)
[22:31:04] [Craft Scheduler Thread - 10799/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
[22:31:04] [Craft Scheduler Thread - 10799/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[22:31:04] [Craft Scheduler Thread - 10799/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:31:04] [Craft Scheduler Thread - 10799/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[22:31:04] [Craft Scheduler Thread - 10799/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[22:31:04] [Craft Scheduler Thread - 10799/WARN]: 	at java.lang.Thread.run(Thread.java:748)`

**Comment by Louis-D** [comment]
How do I not use absolute paths?

**Comment by Rsl1122** [comment]
This issue is caused by Linux File Permission system.

@Fuzzlemann managed to reproduce it & fixed the issue:
- Give the write/read access to the data folder to the user running the Minecraft server.

That should fix it.

**Comment by Louis-D** [comment]
How do I place the files outside of the plugins folder?

**Comment by Fuzzlemann** [comment]
Your configuration "/website/statistics" is correct; you just need to give your minecraft Linux user permissions on the "statistics" folder.
1. Set the owner of statistics to the minecraft Linux user -> `sudo chown <user>: /website/statistics`
2. (unsecure) Set the permissions of the statistics folder to 777 ->`sudo chmod 777 /website/statistics`

**Comment by Louis-D** [comment]
The permissions are correct. Might this be because of docker?
