### ISSUE TITLE
IllegalStateException: Stack Trace was null

### ISSUE THREAD

**Issue by Fuzzlemann** [Rsl1122/Plan-PlayerAnalytics#237]
```
[22:08:56 ERROR]: [Plan] main.java.com.djrapitops.plan.Plan Caught java.lang.IllegalStateException: Stack Trace was null. It has been logged to Errors.txt
[22:08:56 ERROR]: Error occurred while enabling Plan v3.6.2 (Is it up to date?)
java.lang.IllegalStateException: Stack Trace was null
        at com.djrapitops.plugin.utilities.log.ErrorObject.<init>(ErrorObject.java:14) ~[?:?]
        at com.djrapitops.plugin.utilities.log.ErrorLogManager.lambda$readFile$0(ErrorLogManager.java:87) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_144]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_144]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_144]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_144]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_144]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_144]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_144]
        at com.djrapitops.plugin.utilities.log.ErrorLogManager.readFile(ErrorLogManager.java:88) ~[?:?]
        at com.djrapitops.plugin.utilities.log.ErrorLogManager.addError(ErrorLogManager.java:46) ~[?:?]
        at com.djrapitops.plugin.utilities.log.PluginLog.toLog(PluginLog.java:107) ~[?:?]
        at main.java.com.djrapitops.plan.Log.toLog(Log.java:110) ~[?:?]
        at main.java.com.djrapitops.plan.Plan.onEnable(Plan.java:225) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit.jar:git-Paper-1169]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [craftbukkit.jar:git-Paper-1169]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Paper-1169]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376) [craftbukkit.jar:git-Paper-1169]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:325) [craftbukkit.jar:git-Paper-1169]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441) [craftbukkit.jar:git-Paper-1169]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402) [craftbukkit.jar:git-Paper-1169]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340) [craftbukkit.jar:git-Paper-1169]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [craftbukkit.jar:git-Paper-1169]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [craftbukkit.jar:git-Paper-1169]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
```

This happens if some exception at startup occurs, when using PaperSpigot the Plugin does not work at all because if an exception / error at startup of the plugin happens, it's deactivated on an instant.
But it's not only occurring on startup, but at some other exceptions as well.
Both Windows & Linux

**Comment by Rsl1122** [comment]
I've been trying to get reproduce exception with 100 threads logging 500 different exceptions but so far no luck.
Which means that either the issue is fixed, or that the test is not catching the issue.
