### ISSUE TITLE
AbstractMethodError onEnable [1.8.3 - 1.8.8]

### ISSUE THREAD

**Issue by Rsl1122** [Rsl1122/Plan-PlayerAnalytics#309]
```
java.lang.AbstractMethodError: org.sqlite.Conn.isValid(I)Z
    at org.apache.commons.dbcp2.DelegatingConnection.isValid(DelegatingConnection.java:918) ~[?:?]
    at org.apache.commons.dbcp2.PoolableConnection.validate(PoolableConnection.java:283) ~[?:?]
    at org.apache.commons.dbcp2.PoolableConnectionFactory.validateConnection(PoolableConnectionFactory.java:357) ~[?:?]
    at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:2307) ~[?:?]
    at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2290) ~[?:?]
    at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:2039) ~[?:?]
    at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1533) ~[?:?]
    at main.java.com.djrapitops.plan.database.databases.SQLDB.getConnection(SQLDB.java:294) ~[?:?]
    at main.java.com.djrapitops.plan.database.tables.Table.getConnection(Table.java:66) ~[?:?]
    at main.java.com.djrapitops.plan.database.tables.VersionTable.isNewDatabase(VersionTable.java:41) ~[?:?]
    at main.java.com.djrapitops.plan.database.databases.SQLDB.isNewDatabase(SQLDB.java:219) ~[?:?]
    at main.java.com.djrapitops.plan.database.databases.SQLDB.setupDatabase(SQLDB.java:109) ~[?:?]
    at main.java.com.djrapitops.plan.database.databases.SQLDB.init(SQLDB.java:74) ~[?:?]
    at main.java.com.djrapitops.plan.Plan.initDatabase(Plan.java:354) ~[?:?]
    at main.java.com.djrapitops.plan.Plan.onEnable(Plan.java:162) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d"]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
```
Caused by SQLite version in these server versions not supporting Apache BasicDataSource.

**Comment by Rsl1122** [comment]
Solution is to use a single sqlite connection instead of many.

**Comment by Rsl1122** [comment]
Tested a simple solution of swapping back to 3.6.4 SQLite Connection - SQLite speed dropped to 1/2 (1m 36s vs 48s DBTestSuite run)

Not sure how much it actually affects performance since the test methods have to constantly recreate the database.
