### ISSUE TITLE
IllegalArgumentException on planbungee command.

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#360]
Plan v4.0.2
Bungee setup. Trying to reload with ```/planbungee``` from BungeeCord console.

```
[00:14:39] [Console Command Thread #0/INFO]: An internal error occurred whilst executing this command, please check the console log for details.
[00:14:39] [Console Command Thread #0/WARN]: Error in dispatching command
java.lang.IllegalArgumentException: No task with id 6
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:168) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at net.md_5.bungee.scheduler.BungeeScheduler.cancel(BungeeScheduler.java:41) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at com.djrapitops.plugin.task.bungee.AbsBungeeRunnable.cancel(AbsBungeeRunnable.java:80) ~[?:?]
	at com.djrapitops.plugin.task.AbsRunnable.cancel(AbsRunnable.java:52) ~[?:?]
	at main.java.com.djrapitops.plan.systems.queue.Consumer.stop(Consumer.java:46) ~[?:?]
	at main.java.com.djrapitops.plan.systems.queue.Setup.stop(Setup.java:36) ~[?:?]
	at main.java.com.djrapitops.plan.systems.queue.Queue.stop(Queue.java:58) ~[?:?]
	at main.java.com.djrapitops.plan.systems.queue.Queue.stopAndReturnLeftovers(Queue.java:49) ~[?:?]
	at main.java.com.djrapitops.plan.PlanBungee.onDisable(PlanBungee.java:125) ~[?:?]
	at main.java.com.djrapitops.plan.PlanBungee.restart(PlanBungee.java:191) ~[?:?]
	at main.java.com.djrapitops.plan.command.commands.ReloadCommand.onCommand(ReloadCommand.java:48) ~[?:?]
	at com.djrapitops.plugin.command.bungee.BungeeCommand.execute(BungeeCommand.java:26) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:168) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:115) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.github.waterfallmc.waterfall.console.WaterfallConsole.lambda$runCommand$0(WaterfallConsole.java:43) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by Rsl1122** [comment]
Fixed by fixing #368
