### ISSUE TITLE
IllegalStateException - Queue full when executing "/plan analyze" after import of >1000 players

### ISSUE THREAD

**Issue by MattJF90** [Rsl1122/Plan-PlayerAnalytics#38]
**Plan Version:** 2.7.3
**Server Version:** Spigot 1.10.2
**Database Type:** mysql
**Command Causing Issue:** /plan analyze

**Description:**
After importing data from OnTime into the Plan database, I am no longer able to perform an analysis on the server.

This issue seems to be the result of an ArrayBlockingQueue being used with a capacity of 1,000. As approximately 1,300 players were imported, this is exceeding the current limit that Plan can handle.

**Steps to Reproduce:**

1. Execute /plan manage import OnTime -a
2. Wait until the import is complete.
3. (Optional) Restart the server.
4. Execute /plan analyze

**Proposed Solution:**
Replace all instances of
`new ArrayBlockingQueue(1000);`
with either a larger value, or a value which can be set in the config.

**Stack Trace - Console:**
```
04.03 17:38:28 [Server] WARN Exception in thread "Craft Scheduler Thread - 65" 
04.03 17:38:28 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Plan v2.7.3 generated an exception while executing task 266536
04.03 17:38:28 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
04.03 17:38:28 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
04.03 17:38:28 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
04.03 17:38:28 [Server] INFO at java.lang.Thread.run(Thread.java:745)
04.03 17:38:28 [Server] INFO Caused by: java.lang.IllegalStateException: Queue full
04.03 17:38:28 [Server] INFO at java.util.AbstractQueue.add(AbstractQueue.java:98)
04.03 17:38:28 [Server] INFO at java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:312)
04.03 17:38:28 [Server] INFO at main.java.com.djrapitops.plan.data.cache.DataCacheGetQueue.scheduleForGet(DataCacheGetQueue.java:36)
04.03 17:38:28 [Server] INFO at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.getUserDataForProcessing(DataCacheHandler.java:143)
04.03 17:38:28 [Server] INFO at main.java.com.djrapitops.plan.data.cache.InspectCacheHandler.cache(InspectCacheHandler.java:56)
04.03 17:38:28 [Server] INFO at main.java.com.djrapitops.plan.utilities.Analysis$1.lambda$run$1(Analysis.java:72)
04.03 17:38:28 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
04.03 17:38:28 [Server] INFO at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
04.03 17:38:28 [Server] INFO at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
04.03 17:38:28 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
04.03 17:38:28 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
04.03 17:38:28 [Server] INFO at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
04.03 17:38:28 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
04.03 17:38:28 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
04.03 17:38:28 [Server] INFO at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
04.03 17:38:28 [Server] INFO at main.java.com.djrapitops.plan.utilities.Analysis$1.run(Analysis.java:71)
04.03 17:38:28 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
04.03 17:38:28 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
04.03 17:38:28 [Server] INFO ... 3 more
```

**Comment by Rsl1122** [comment]
I'll make the values configurable in the next update.

Before the blocking queue was introduced Plan would have made 1300 (the amount of players) new tasks to handle each get request and I thought it was too many.

Hopefully the large number of players will not cause any other issues after this one is fixed.
