### ISSUE TITLE
Sqlite autocommit error

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#4]
Environment: Spigot 1.11.2 latest, Plan 2.3.0, and a plethora of plugins supporting multiverse. Every five minutes, the log shows:

> [10:25:22 WARN]: java.sql.SQLException: database in auto-commit mode
[10:25:22 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.commit(JDBC3Connection.java:164)
[10:25:22 WARN]:        at com.djrapitops.plan.database.databases.SQLDB.saveMultipleUserData(SQLDB.java:647)
[10:25:22 WARN]:        at com.djrapitops.plan.data.cache.DataCacheHandler.saveCachedUserData(DataCacheHandler.java:159)
[10:25:22 WARN]:        at com.djrapitops.plan.data.cache.DataCacheHandler$1.run(DataCacheHandler.java:88)
[10:25:22 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[10:25:22 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[10:25:22 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[10:25:22 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[10:25:22 WARN]:        at java.lang.Thread.run(Thread.java:745)

**Comment by Rsl1122** [comment]
Ah, dang this is caused because there are two async tasks, one saving playerdata and one saving serverdata.
I'll try to figure something out. I'll get back to you.

**Comment by SlimeDog** [comment]
thanks.

**Comment by Rsl1122** [comment]
Should be fixed

**Comment by SlimeDog** [comment]
Seems to be fixed in 2.3.1
