### ISSUE TITLE
NullPointerException | InspectCacheClearTask

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#42]
Spigot 1.11.2, Plan 2.8.1

If anything, NPEs are more frequent.

> [07:41:07 WARN]: [Plan] Task #5209 for Plan v2.8.1 generated an exception
java.lang.NullPointerException
at main.java.com.djrapitops.plan.data.cache.InspectCacheHandler$2.run(InspectCacheHandler.java:72) ~[?:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar-2017-03-10-0649:git-Spigot-283de8b-eac8591]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar-2017-03-10-0649:git-Spigot-283de8b-eac8591]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.2.jar-2017-03-10-0649:git-Spigot-283de8b-eac8591]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar-2017-03-10-0649:git-Spigot-283de8b-eac8591]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar-2017-03-10-0649:git-Spigot-283de8b-eac8591]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar-2017-03-10-0649:git-Spigot-283de8b-eac8591]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by Rsl1122** [comment]
This NPE occurs during inspect cache clear task so it doesn't affect saving, I'll fix it in the next update.
If you want to see them less often (till it's fixed) change ClearFromInspectCacheAfterXMinutes to higher value.

**Comment by SlimeDog** [comment]
OK. It looks like 

> ClearFromInspectCacheAfterXMinutes: 10

is adequate.

**Comment by SlimeDog** [comment]
It looks like
> ClearFromInspectCacheAfterXMinutes: 20

does not stop the NPEs. Here is the business end of my config:
> Settings:
  Locale: default
  UseTextUI: false
  Data:
    GatherLocations: true
  Analysis:
    LogProgressOnConsole: false
    MinutesPlayedUntilConsidiredActive: 10
  Cache:
    Processing:
      GetLimit: 2000
      SaveLimit: 1000
      ClearLimit: 1000
    AnalysisCache:
      RefreshAnalysisCacheOnEnable: true
      RefreshEveryXMinutes: 5
    InspectCache:
      ClearFromInspectCacheAfterXMinutes: 20
    DataCache:
      SaveEveryXMinutes: 2
      ClearCacheEveryXSaves: 5

Can you recommend settings that will stop the NPEs?

**Comment by SlimeDog** [comment]
> ClearFromInspectCacheAfterXMinutes: 30

does do it either. :(

**Comment by Rsl1122** [comment]
It's because for some reason it tries to remove already removed data from cache. I'll upload a fix later this evening.
