### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#44]
Spigot 1.11.2, Plan 2.8.2, 3:00 after server start:

> [12:03:30 INFO]: [Plan] Analysis | Starting Boot Analysis..
[12:03:30 WARN]: [Plan] Plugin Plan v2.8.2 generated an exception while executing task 842
java.util.ConcurrentModificationException
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380) ~[?:1.8.0_121]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_121]
        at main.java.com.djrapitops.plan.utilities.AnalysisUtils.transformSessionDataToLengths(AnalysisUtils.java:89) ~[?:?]
        at main.java.com.djrapitops.plan.utilities.Analysis$1.run(Analysis.java:150) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar-2017-03-10-0649:git-Spigot-283de8b-eac8591]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.11.2.jar-2017-03-10-0649:git-Spigot-283de8b-eac8591]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[12:04:35 INFO]: [StreetlightsAdvanced] Activated streetlights in world_blackdog
[12:04:35 INFO]: [StreetlightsAdvanced] Activated streetlights in world_city

**Comment by Rsl1122** [comment]
Did someone log in or log out before this occurred?

**Comment by SlimeDog** [comment]
No. Server is quiescent.

**Comment by Rsl1122** [comment]
Failed to replicate with test:
```
@Override
    public boolean runTest() throws Exception {
        ArrayList<SessionData> d = new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            d.addAll(SessionDataListCreator.createRandomSessionDataList());
        }
        boolean passed = AnalysisUtils.transformSessionDataToLengths(d).size() == 5000;
        if (passed) {
            pass();
        } else {
            fail("");
        }
        return passed;
    }
```
Does it throw it every time the server is started or /plan analyze is run?
