### ISSUE TITLE
NPE main.java.com.djrapitops.plan.command.commands.RegisterCommandFilter.isSensibleCommand(RegisterCommandFilter.java:72)

### ISSUE THREAD

**Issue by Rbot48** [Rsl1122/Plan-PlayerAnalytics#468]
The following error is displayed when trying to use some RedProtect commands such as /rp addleader \<player\>, and the player who used the command gets "An internal error occurred while attempting to perform this command":
```
11.12 00:56:34 [Server] INFO ... 5 more
11.12 00:56:34 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) ~[TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
11.12 00:56:34 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_101]
11.12 00:56:34 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_101]
11.12 00:56:34 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
11.12 00:56:34 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
11.12 00:56:34 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
11.12 00:56:34 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1203) ~[TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
11.12 00:56:34 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1404) ~[TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
11.12 00:56:34 [Server] INFO at java.util.logging.Logger.log(Logger.java:875) ~[?:1.8.0_101]
11.12 00:56:34 [Server] INFO at java.util.logging.Logger.doLog(Logger.java:765) ~[?:1.8.0_101]
11.12 00:56:34 [Server] INFO at java.util.logging.Logger.log(Logger.java:738) ~[?:1.8.0_101]
11.12 00:56:34 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.util.ForwardLogHandler.publish(ForwardLogHandler.java:33) ~[TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
11.12 00:56:34 [Server] INFO at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:609) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
11.12 00:56:34 [Server] INFO at org.apache.logging.log4j.core.Logger.log(Logger.java:110) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
11.12 00:56:34 [Server] INFO at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
11.12 00:56:34 [Server] INFO at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:400) ~[TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
11.12 00:56:34 [Server] INFO at org.apache.logging.log4j.core.filter.AbstractFilterable.isFiltered(AbstractFilterable.java:124) ~[TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
11.12 00:56:34 [Server] INFO at org.apache.logging.log4j.core.filter.CompositeFilter.filter(CompositeFilter.java:231) ~[TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
11.12 00:56:34 [Server] INFO at main.java.com.djrapitops.plan.command.commands.RegisterCommandFilter.filter(RegisterCommandFilter.java:35) ~[Plan-4.1.3.1.jar:2.1.1]
11.12 00:56:34 [Server] INFO at main.java.com.djrapitops.plan.command.commands.RegisterCommandFilter.validateMessage(RegisterCommandFilter.java:62) ~[Plan-4.1.3.1.jar:2.1.1]
11.12 00:56:34 [Server] INFO at main.java.com.djrapitops.plan.command.commands.RegisterCommandFilter.validateMessage(RegisterCommandFilter.java:66) ~[Plan-4.1.3.1.jar:2.1.1]
11.12 00:56:34 [Server] INFO at main.java.com.djrapitops.plan.command.commands.RegisterCommandFilter.isSensibleCommand(RegisterCommandFilter.java:72) ~[Plan-4.1.3.1.jar:2.1.1]
11.12 00:56:34 [Server] INFO Caused by: java.lang.NullPointerException
11.12 00:56:34 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
11.12 00:56:34 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
11.12 00:56:34 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
11.12 00:56:34 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
11.12 00:56:34 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:808) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
11.12 00:56:34 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:46) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
11.12 00:56:34 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_101]
11.12 00:56:34 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_101]
11.12 00:56:34 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NullPointerException
11.12 00:56:34 [Server] FATAL Error executing task
```

### Server Information
**Plan Version:** 4.1.3.1
**Server:** Paper 1.10.2-R0.1-SNAPSHOT git-TacoSpigot-7af2abbe (MC: 1.10.2)
**Database:** MySQL schema v13

### Logged Errors
```
java.io.FileNotFoundException: File not found inside jar: web/error.html
   main.java.com.djrapitops.plan.utilities.file.FileUtil.lines(FileUtil.java:83)
   main.java.com.djrapitops.plan.utilities.file.FileUtil.lines(FileUtil.java:43)
   main.java.com.djrapitops.plan.utilities.file.FileUtil.getStringFromResource(FileUtil.java:28)
   main.java.com.djrapitops.plan.systems.webserver.response.ErrorResponse.(ErrorResponse.java:29)
   main.java.com.djrapitops.plan.systems.webserver.response.NotFoundResponse.(NotFoundResponse.java:18)
   main.java.com.djrapitops.plan.systems.info.BukkitInformationManager.lambda$cachePlayer$0(BukkitInformationManager.java:122)
   main.java.com.djrapitops.plan.systems.webserver.PageCache.cachePage(PageCache.java:96)
   main.java.com.djrapitops.plan.systems.info.BukkitInformationManager.cachePlayer(BukkitInformationManager.java:117)
   main.java.com.djrapitops.plan.systems.cache.SessionCache.cacheSession(SessionCache.java:34)
   main.java.com.djrapitops.plan.systems.listeners.PlanPlayerListener.onPlayerJoin(PlanPlayerListener.java:108)
   com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor938.execute(Unknown Source)
   org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44)
   co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
   org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
   org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
   org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
   net.minecraft.server.v1_10_R1.PlayerList.onPlayerJoin(PlayerList.java:357)
   net.minecraft.server.v1_10_R1.PlayerList.a(PlayerList.java:177)
   net.minecraft.server.v1_10_R1.LoginListener.b(LoginListener.java:144)
   net.minecraft.server.v1_10_R1.LoginListener.E_(LoginListener.java:54)
   net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:233)
   net.minecraft.server.v1_10_R1.ServerConnection.c(ServerConnection.java:152)
   net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:903)
   net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
   net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740)
   net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639)
   java.lang.Thread.run(Thread.java:745)
```
- [ ] Fixed

**Comment by Rsl1122** [comment]
Hmm, this will be tough to debug because of so many layers above my code before the exception occurs.

The second one is caused by not restarting after updating plan jar

**Comment by Rbot48** [comment]
Yes, the first one is from multicraft, so it's upside down
