### ISSUE TITLE
IllegalPluginAccessException: Plugin attempted to register task while disabled

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#476]
Plan 4.1.3.1

Error occurs near the end of the shutdown process when restarting (full shutdown / start-up) the bukkit server.
```
[13:36:02] [Thread-24/WARN]: Exception in thread "Thread-24" org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[13:36:02] [Thread-24/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:413)
[13:36:02] [Thread-24/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:148)
[13:36:02] [Thread-24/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:122)
[13:36:02] [Thread-24/WARN]: 	at org.bukkit.scheduler.BukkitRunnable.runTaskLaterAsynchronously(BukkitRunnable.java:94)
[13:36:02] [Thread-24/WARN]: 	at com.djrapitops.plugin.task.bukkit.AbsBukkitRunnable.runTaskLaterAsynchronously(AbsBukkitRunnable.java:63)
[13:36:02] [Thread-24/WARN]: 	at main.java.com.djrapitops.plan.database.databases.SQLDB.scheduleClean(SQLDB.java:96)
[13:36:02] [Thread-24/WARN]: 	at main.java.com.djrapitops.plan.database.databases.SQLDB.init(SQLDB.java:74)
[13:36:02] [Thread-24/WARN]: 	at main.java.com.djrapitops.plan.ShutdownHook.run(ShutdownHook.java:56)
```

**Comment by Rsl1122** [comment]
Caused by Database Init during save of active sessions.
