### ISSUE TITLE
Error on plugin disable

### ISSUE THREAD

**Issue by i0xHeX** [Rsl1122/Plan-PlayerAnalytics#482]
On plugin disable (manual or server stop) there is an exception:

    20.12 23:19:50 [Server] WARN Exception in thread "Thread-32" 
    20.12 23:19:50 [Server] WARN org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
    20.12 23:19:50 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:403)
    20.12 23:19:50 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:144)
    20.12 23:19:50 [Server] WARN at org.bukkit.scheduler.BukkitRunnable.runTaskTimerAsynchronously(BukkitRunnable.java:133)
    20.12 23:19:50 [Server] WARN at com.djrapitops.plugin.task.bukkit.AbsBukkitRunnable.runTaskTimerAsynchronously(AbsBukkitRunnable.java:79)
    20.12 23:19:50 [Server] WARN at main.java.com.djrapitops.plan.database.databases.SQLiteDB.startConnectionPingTask(SQLiteDB.java:106)
    20.12 23:19:50 [Server] WARN at main.java.com.djrapitops.plan.database.databases.SQLiteDB.setupDataSource(SQLiteDB.java:47)
    20.12 23:19:50 [Server] WARN at main.java.com.djrapitops.plan.database.databases.SQLDB.init(SQLDB.java:72)
    20.12 23:19:50 [Server] WARN at main.java.com.djrapitops.plan.ShutdownHook.run(ShutdownHook.java:56)

**Comment by Rsl1122** [comment]
Breaks active session saving on shutdown for sqlite configurations, thus high priority

**Comment by SlimeDog** [comment]
Spigot 1.12.2 latest
Plan 4.1.4

This occurs on **/stop**, even if there is no active session.
```
[08:36:54 WARN]: Exception in thread "Thread-138" 
[08:36:54 WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[08:36:54 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:403)
[08:36:54 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:144)
[08:36:54 WARN]:        at org.bukkit.scheduler.BukkitRunnable.runTaskTimerAsynchronously(BukkitRunnable.java:133)
[08:36:54 WARN]:        at com.djrapitops.plugin.task.bukkit.AbsBukkitRunnable.runTaskTimerAsynchronously(AbsBukkitRunnable.java:79)
[08:36:54 WARN]:        at main.java.com.djrapitops.plan.database.databases.SQLiteDB.startConnectionPingTask(SQLiteDB.java:106)
[08:36:54 WARN]:        at main.java.com.djrapitops.plan.database.databases.SQLiteDB.setupDataSource(SQLiteDB.java:47)
[08:36:54 WARN]:        at main.java.com.djrapitops.plan.database.databases.SQLDB.init(SQLDB.java:72)
[08:36:54 WARN]:        at main.java.com.djrapitops.plan.ShutdownHook.run(ShutdownHook.java:56)
```
