### ISSUE TITLE
/plan throws an error

### ISSUE THREAD

**Issue by hyperjoke** [Rsl1122/Plan-PlayerAnalytics#485]
When i type /plan minecraft returns me "An internal error occurred while attempting to perform this command"

EDIT: 
MC version: 1.11.1
plan version: 4.1.4

Here is console log:
 
```
[14:26:20] [pool-3-thread-122/INFO]: [Plan] Cleaning the database.
[14:26:20] [pool-3-thread-122/INFO]: [Plan] Clean complete.
[14:26:23] [Server thread/INFO]: hyperjoker13 issued server command: /plan
[14:26:23] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'plan' in plugin Plan v4.1.4
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Bukkit-c19c293]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit.jar:git-Bukkit-c19c293]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:629) ~[craftbukkit.jar:git-Bukkit-c19c293]
at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1295) [craftbukkit.jar:git-Bukkit-c19c293]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1155) [craftbukkit.jar:git-Bukkit-c19c293]
at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit.jar:git-Bukkit-c19c293]
at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit.jar:git-Bukkit-c19c293]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Bukkit-c19c293]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [craftbukkit.jar:git-Bukkit-c19c293]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:695) [craftbukkit.jar:git-Bukkit-c19c293]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360) [craftbukkit.jar:git-Bukkit-c19c293]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650) [craftbukkit.jar:git-Bukkit-c19c293]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit.jar:git-Bukkit-c19c293]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
at com.djrapitops.plugin.command.bukkit.BukkitCommand.onCommand(BukkitCommand.java:28) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Bukkit-c19c293]
... 15 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_77]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit.jar:git-Bukkit-c19c293]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit.jar:git-Bukkit-c19c293]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_77]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_77]
at com.djrapitops.plugin.command.bukkit.BukkitCommand.onCommand(BukkitCommand.java:28) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Bukkit-c19c293]
... 15 more
[14:26:40] [pool-3-thread-134/INFO]: [Plan] Analysis | Starting Boot Analysis..
[14:26:40] [pool-3-thread-134/INFO]: [Plan] Analysis | Beginning analysis of user data..
[14:26:40] [pool-3-thread-134/INFO]: [Plan] Analysis | Fetching Data..
[14:26:40] [pool-3-thread-134/INFO]: [Plan] Analysis | Data Fetched (0 users, took 10ms), beginning Analysis of data..
[14:26:40] [pool-3-thread-134/INFO]: [Plan] Analysis | Analyzing additional data sources (3rd party)
[14:26:40] [pool-3-thread-134/INFO]: [Plan] Analysis | Analysis Complete. (took 150 ms) 
```

Sorry for my bad English,
hyperjoke

**Comment by Rsl1122** [comment]
Possibly caused by using CraftBukkit instead of Spigot.
Related to https://github.com/Rsl1122/Abstract-Plugin-Framework/issues/4
