### ISSUE TITLE
NPE thrown for /plan analyze

### ISSUE THREAD

**Issue by Alphexon** [Rsl1122/Plan-PlayerAnalytics#51]
**Plan Version:**  2.8.1
**Server Version:** Spigot-1.11.2
**Database Type:** SQLite
**Command Causing Issue:** /plan analyze

**Description:**
NPE is thrown, and the analysis times out.

**Stack Trace - Console/Errors.txt contents:**
```
11.03 21:09:05 [Server] INFO java.lang.NullPointerException
11.03 21:09:05 [Server] INFO at main.java.com.djrapitops.plan.utilities.AnalysisUtils.lambda$transformSessionDataToLengths$3(AnalysisUtils.java:91) ~[?:?]
11.03 21:09:05 [Server] INFO at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_112]
11.03 21:09:05 [Server] INFO at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_112]
11.03 21:09:05 [Server] INFO at main.java.com.djrapitops.plan.utilities.AnalysisUtils.transformSessionDataToLengths(AnalysisUtils.java:90) ~[?:?]
11.03 21:09:05 [Server] INFO at main.java.com.djrapitops.plan.utilities.Analysis$1.run(Analysis.java:150) ~[?:?]
11.03 21:09:05 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.jar:git-Spigot-d4f98a3-cb61ac0]
11.03 21:09:05 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.11.jar:git-Spigot-d4f98a3-cb61ac0]
11.03 21:09:05 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
11.03 21:09:05 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
11.03 21:09:05 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

**Comment by Rsl1122** [comment]
This has been fixed in 2.8.2
Please download the latest version.
