### ISSUE TITLE
[4.1.5-DEV2] NoClassDefFoundError when running /planbungee

### ISSUE THREAD

**Issue by Rbot48** [Rsl1122/Plan-PlayerAnalytics#520]
```
03.02 16:43:01 [Server] ERROR Exception in thread "Console Command Thread #0" java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
03.02 16:43:01 [Server] ERROR at com.djrapitops.plugin.command.HelpCommand.onCommand(TreeCommand.java:191)
03.02 16:43:01 [Server] ERROR at com.djrapitops.plugin.command.TreeCommand.onCommand(TreeCommand.java:150)
03.02 16:43:01 [Server] ERROR at com.djrapitops.plugin.command.TreeCommand.sendDefaultCommand(TreeCommand.java:97)
03.02 16:43:01 [Server] ERROR at com.djrapitops.plugin.command.TreeCommand.onCommand(TreeCommand.java:112)
03.02 16:43:01 [Server] ERROR at com.djrapitops.plugin.command.bungee.BungeeCommand.execute(BungeeCommand.java:26)
03.02 16:43:01 [Server] ERROR at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:168)
03.02 16:43:01 [Server] ERROR at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:115)
03.02 16:43:01 [Server] ERROR at io.github.waterfallmc.waterfall.console.WaterfallConsole.lambda$runCommand$0(WaterfallConsole.java:43)
03.02 16:43:01 [Server] ERROR at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
03.02 16:43:01 [Server] ERROR at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
03.02 16:43:01 [Server] ERROR at java.lang.Thread.run(Thread.java:748)
```

Waterfall version git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164

**Comment by Rsl1122** [comment]
Caused by removal of StringUtils as a shade dependency & a single line in Abstract Plugin Framework using the old StringUtils instead of lang3

UGH :D
https://github.com/Rsl1122/Abstract-Plugin-Framework/issues/10
