### ISSUE TITLE
Will not work on Paperspigot 1.7.10 (Cause: Old version of java in use on the server -Rsl)

### ISSUE THREAD

**Issue by TheUpBeatGamer** [Rsl1122/Plan-PlayerAnalytics#55]
**Plan Version:** 2.8.4
**Server Version:** PaperSpigot 1.7.10
**Console Error:** 

```
[00:04:01] [Server thread/ERROR]: Could not load 'plugins/Plan-2.8.4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: main/java/com/djrapitops/plan/Plan : Unsupported major.minor version 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:336) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:258) [spigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:369) [spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:169) [spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:494) [spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-PaperSpigot-1f7d532]
Caused by: java.lang.UnsupportedClassVersionError: main/java/com/djrapitops/plan/Plan : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_111]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803) ~[?:1.7.0_111]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_111]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_111]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_111]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_111]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_111]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_111]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_111]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_111]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_111]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_111]
	at java.lang.Class.forName(Class.java:278) ~[?:1.7.0_111]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-PaperSpigot-1f7d532]
	... 6 more
```

**Comment by Rsl1122** [comment]
This is caused because your server is using older version of java than what the plugin was compiled with.
Please update your server java version to the latest version. It should fix the issue.

**Comment by TheUpBeatGamer** [comment]
I am using Java 8?

**Comment by Rsl1122** [comment]
Plan 2.8.4 was compiled with java version "1.8.0_121"
You can check your java version with `java -version`
