### ISSUE TITLE
Sponge not loading Apache DBCP2 due to org.apache namespace (MySQL does not function)

### ISSUE THREAD

**Issue by Rsl1122** [Rsl1122/Plan-PlayerAnalytics#562]
```
java.lang.NoClassDefFoundError: org/apache/commons/dbcp2/BasicDataSource
        at com.djrapitops.plan.system.database.databases.sql.MySQLDB.setupDataSource(MySQLDB.java:25) ~[MySQLDB.class:?]
        at com.djrapitops.plan.system.database.databases.sql.SQLDB.init(SQLDB.java:99) ~[SQLDB.class:?]
        at com.djrapitops.plan.system.database.DBSystem.getActiveDatabaseByName(DBSystem.java:82) ~[DBSystem.class:?]
        at com.djrapitops.plan.system.database.ServerDBSystem.initDatabase(ServerDBSystem.java:25) ~[ServerDBSystem.class:?]
        at com.djrapitops.plan.system.database.DBSystem.enable(DBSystem.java:47) ~[DBSystem.class:?]
        at com.djrapitops.plan.system.PlanSystem.enable(PlanSystem.java:98) ~[PlanSystem.class:?]
        at com.djrapitops.plan.system.SpongeSystem.enable(SpongeSystem.java:62) ~[SpongeSystem.class:?]
        at com.djrapitops.plan.PlanSponge.onEnable(PlanSponge.java:56) ~[PlanSponge.class:?]
        at com.djrapitops.plan.PlanSponge.onServerStart(PlanSponge.java:39) ~[PlanSponge.class:?]
        at org.spongepowered.common.event.listener.GameStartedServerEventListener_PlanSponge_onServerStart2.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2611-7.1.0-BETA-3017]
```
> Forge excludes some packages from loading in mods (prevents inconsistent classloading issues).
You’ll need to shade the package when building. Something like renaming org.apache to gt.creeperface.sponge.shaded.apache or whatever

https://forums.spongepowered.org/t/plugin-external-libraries/21146/8

Fix: Relocate apache DBCP package to another namespace

**Comment by Rsl1122** [comment]
Fixed in commit f1024f67c04fb35d8af017b2b1007481b024e02b
