### ISSUE TITLE
BiGUNNMAN's issue | NPE while saving to cache | GamemodeTimesHandler

### ISSUE THREAD

**Issue by Rsl1122** [Rsl1122/Plan-PlayerAnalytics#57]
**Plan Version:** 2.8.3
**Server Version:** Unknown
**Database Type:** Unknown
**Command Causing Issue:** (None if thrown without commands)

**Description:**
-
**Steps to Reproduce:**
-

**Stack Trace - Console/Errors.txt contents:**
```
[20:52:39] [Craft Scheduler Thread - 591/WARN]: [Plan] Plugin Plan v2.8.3 generated an exception while executing task 929
java.lang.NullPointerException
	at main.java.com.djrapitops.plan.data.handlers.GamemodeTimesHandler.saveToCache(GamemodeTimesHandler.java:73) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler$3.process(DataCacheHandler.java:239) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.getUserDataForProcessing(DataCacheHandler.java:146) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.getUserDataForProcessing(DataCacheHandler.java:159) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.saveHandlerDataToCache(DataCacheHandler.java:242) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.lambda$saveHandlerDataToCache$1(DataCacheHandler.java:229) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_121]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_121]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[?:1.8.0_121]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_121]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_121]
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870) ~[?:1.8.0_121]
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467) ~[?:1.8.0_121]
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324) ~[?:1.8.0_121]
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:405) ~[?:1.8.0_121]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) ~[?:1.8.0_121]
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) ~[?:1.8.0_121]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583) ~[?:1.8.0_121]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.saveHandlerDataToCache(DataCacheHandler.java:228) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler$1.run(DataCacheHandler.java:106) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1063]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.11.2.jar:git-Paper-1063]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.11.2.jar:git-Paper-1063]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by Rsl1122** [comment]
Caught errors with Debugger #47 

```
[Mar 16 08:40:46] Test com.djrapitops.plandebugger.tests.independent.handlers.CorruptLastGamemodeChangeTest3: Running..
[Mar 16 08:40:46] Test com.djrapitops.plandebugger.tests.independent.handlers.CorruptLastGamemodeChangeTest3: §cERROR java.lang.NullPointerException
[Mar 16 08:40:46]   main.java.com.djrapitops.plan.data.handlers.GamemodeTimesHandler.handleChangeEvent(GamemodeTimesHandler.java:54)
[Mar 16 08:40:46]   com.djrapitops.plandebugger.tests.independent.handlers.CorruptLastGamemodeChangeTest3.runTest(CorruptLastGamemodeChangeTest3.java:45)
[Mar 16 08:40:46]   com.djrapitops.plandebugger.tests.TestRunner.runAllTests(TestRunner.java:40)
[Mar 16 08:40:46]   com.djrapitops.plandebugger.DebugTask.run(DebugTask.java:36)
[Mar 16 08:40:46]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[Mar 16 08:40:46]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[Mar 16 08:40:46]   java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[Mar 16 08:40:46]   java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[Mar 16 08:40:46]   java.lang.Thread.run(Unknown Source)
[Mar 16 08:40:46] Test com.djrapitops.plandebugger.tests.independent.handlers.CorruptCurrentGamemodeChangeTest: Running..
[Mar 16 08:40:46] Test com.djrapitops.plandebugger.tests.independent.handlers.CorruptCurrentGamemodeChangeTest: §cERROR java.lang.NullPointerException
[Mar 16 08:40:46]   main.java.com.djrapitops.plan.data.handlers.GamemodeTimesHandler.handleChangeEvent(GamemodeTimesHandler.java:54)
[Mar 16 08:40:46]   com.djrapitops.plandebugger.tests.independent.handlers.CorruptCurrentGamemodeChangeTest.runTest(CorruptCurrentGamemodeChangeTest.java:45)
[Mar 16 08:40:46]   com.djrapitops.plandebugger.tests.TestRunner.runAllTests(TestRunner.java:40)
[Mar 16 08:40:46]   com.djrapitops.plandebugger.DebugTask.run(DebugTask.java:36)
[Mar 16 08:40:46]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[Mar 16 08:40:46]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[Mar 16 08:40:46]   java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[Mar 16 08:40:46]   java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[Mar 16 08:40:46]   java.lang.Thread.run(Unknown Source)
```
