### ISSUE TITLE
ConcurrentModificationException: null related to TaskCenter

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#584]
Plan v4.3.1
Paper dev 1427 (Spigot 1.12.2)
```
[02:59:50] [Craft Scheduler Thread - 43/WARN]: [Plan] Plugin Plan v4.3.1 generated an exception while executing task 600
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1471) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543) ~[?:?]
	at com.djrapitops.plugin.api.systems.TaskCenter.taskCancelled(TaskCenter.java:56) ~[Plan-4.3.1.jar:?]
	at com.djrapitops.plugin.task.bukkit.AbsBukkitRunnable.cancel(AbsBukkitRunnable.java:87) ~[Plan-4.3.1.jar:?]
	at com.djrapitops.plugin.task.AbsRunnable.cancel(AbsRunnable.java:51) ~[Plan-4.3.1.jar:?]
	at com.djrapitops.plan.system.processing.processors.info.PlayerPageUpdateProcessor$1.run(PlayerPageUpdateProcessor.java:29) ~[Plan-4.3.1.jar:?]
	at com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:39) ~[Plan-4.3.1.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1427]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1427]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1427]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]

```

**Comment by mibby** [comment]
Related error? Plan just continuously spams console with it since v4.3.x. :(

```
[00:04:29] [Craft Scheduler Thread - 391/WARN]: [Plan] Plugin Plan v4.3.1 generated an exception while executing task 166592
java.lang.NullPointerException: null
	at com.djrapitops.plugin.api.systems.TaskCenter.lambda$taskCancelled$0(TaskCenter.java:55) ~[Plan-4.3.1.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1469) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543) ~[?:?]
	at com.djrapitops.plugin.api.systems.TaskCenter.taskCancelled(TaskCenter.java:56) ~[Plan-4.3.1.jar:?]
	at com.djrapitops.plugin.task.bukkit.AbsBukkitRunnable.cancel(AbsBukkitRunnable.java:87) ~[Plan-4.3.1.jar:?]
	at com.djrapitops.plugin.task.AbsRunnable.cancel(AbsRunnable.java:51) ~[Plan-4.3.1.jar:?]
	at com.djrapitops.plan.system.processing.processors.info.PlayerPageUpdateProcessor$1.run(PlayerPageUpdateProcessor.java:29) ~[Plan-4.3.1.jar:?]
	at com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:39) ~[Plan-4.3.1.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1427]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1427]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1427]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
```

**Comment by Rsl1122** [comment]
Looks like both are an issue with the task system of Abstract-Plugin-Framework. I'll fix em both for next dev release on Monday, which will go on full release if everything goes well.

**Comment by Rsl1122** [comment]
Fixed in DEV2
https://github.com/Rsl1122/Plan-PlayerAnalytics/releases/tag/4.3.2-DEV2
