### ISSUE TITLE
Corrupt playerfile? (NPE GameModeTimesHandler)

### ISSUE THREAD

**Issue by OasisMaximus** [Rsl1122/Plan-PlayerAnalytics#59]
Plan version: 2.8.4
Server Version: Spigot-1.11.2
Database Type: MySQL
Command Causing Issue: none

Description:
At about two minute intervals the plugin throws an error, see below for the stacktrace.
I am not a java expert in the slightest, but I suspected it had something to do with gamemodes because of the mention of "GamemodeTimesHandler". I then did /plan analyze to see wether something weird was up, and it gave me another error:

> [10:34:23] [Server thread/INFO]: »[0;32;22m Fetching data to cache..[m
[10:34:23] [ForkJoinPool.commonPool-worker-0/ERROR]: [Plan] Some data might be corrupted: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[10:34:23] [ForkJoinPool.commonPool-worker-0/ERROR]: [Plan] Caugth java.lang.NullPointerException. It has been logged to the Errors.txt
[10:34:25] [Craft Scheduler Thread - 303/INFO]: [Plan] Analysis | Analysis Complete.
[10:34:29] [Server thread/INFO]: [0;37;1m»[0;32;22m Player Analytics - Analysis results[m
[10:34:29] [Server thread/INFO]: [0;37;22m •[0;32;22m Link: [0;37;1mhttp://oasis-mc.us:xxxx/xxxxxxxxx/server[m

NOTE: I manually made the UUID and URL as shown above, but it was a valid UUID of one of our players and the link was also a correct link that worked. The error.txt is listed below.
Nothing out of the ordinary showed up at the webpage, only thing was that the player that the UUID belonged to wasn't mentioned in the webpage.
Since the first error was about gamemodes, I tried switching the gamemode of the player in question to adventure, then back to survival. It gave me another two error, see below for the stacktraces.

I do not know the cause, and I have no clue what the solution is. I am suspecting the essentials file is corrupt somehow? 

First error stacktrace:
```[10:35:41] [Craft Scheduler Thread - 302/WARN]: [Plan] Plugin Plan v2.8.4 generated an exception while executing task 97
java.lang.NullPointerException
	at main.java.com.djrapitops.plan.data.handlers.GamemodeTimesHandler.saveToCache(GamemodeTimesHandler.java:73) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler$3.process(DataCacheHandler.java:239) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.getUserDataForProcessing(DataCacheHandler.java:146) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.getUserDataForProcessing(DataCacheHandler.java:159) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.saveHandlerDataToCache(DataCacheHandler.java:242) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.lambda$saveHandlerDataToCache$1(DataCacheHandler.java:229) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_101]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_101]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_101]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.ForkJoinPool.helpComplete(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[?:1.8.0_101]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[?:1.8.0_101]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_101]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_101]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:1.8.0_101]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.saveHandlerDataToCache(DataCacheHandler.java:228) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler$1.run(DataCacheHandler.java:106) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_101]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]```

Errors.txt contents:
```[Mar 18 10:34:23] main.java.com.djrapitops.plan.utilities.Analysis Caught java.lang.NullPointerException
[Mar 18 10:34:23]   main.java.com.djrapitops.plan.utilities.Analysis.lambda$analyze$5(Analysis.java:139)
[Mar 18 10:34:23]   java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[Mar 18 10:34:23]   java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
[Mar 18 10:34:23]   java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[Mar 18 10:34:23]   java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
[Mar 18 10:34:23]   java.util.concurrent.CountedCompleter.exec(Unknown Source)
[Mar 18 10:34:23]   java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[Mar 18 10:34:23]   java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
[Mar 18 10:34:23]   java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[Mar 18 10:34:23]   java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[Mar 18 10:34:23] ```

Second error stacktraces:
```[10:37:39] [Server thread/ERROR]: Could not pass event PlayerGameModeChangeEvent to Plan v2.8.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.setGameMode(CraftPlayer.java:790) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at com.earth2me.essentials.commands.Commandgamemode.gamemodeOtherPlayers(Commandgamemode.java:89) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.Commandgamemode.run(Commandgamemode.java:42) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:471) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:381) [EssentialsX-2.0.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1345) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1180) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
	at main.java.com.djrapitops.plan.data.handlers.GamemodeTimesHandler.handleChangeEvent(GamemodeTimesHandler.java:55) ~[?:?]
	at main.java.com.djrapitops.plan.data.listeners.PlanGamemodeChangeListener$1.process(PlanGamemodeChangeListener.java:49) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.getUserDataForProcessing(DataCacheHandler.java:146) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.getUserDataForProcessing(DataCacheHandler.java:159) ~[?:?]
	at main.java.com.djrapitops.plan.data.listeners.PlanGamemodeChangeListener.onGamemodeChange(PlanGamemodeChangeListener.java:52) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	... 25 more
[10:37:42] [Craft Scheduler Thread - 312/WARN]: [Plan] Plugin Plan v2.8.4 generated an exception while executing task 97
java.lang.NullPointerException
	at main.java.com.djrapitops.plan.data.handlers.GamemodeTimesHandler.saveToCache(GamemodeTimesHandler.java:73) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler$3.process(DataCacheHandler.java:239) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.getUserDataForProcessing(DataCacheHandler.java:146) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.getUserDataForProcessing(DataCacheHandler.java:159) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.saveHandlerDataToCache(DataCacheHandler.java:242) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.lambda$saveHandlerDataToCache$1(DataCacheHandler.java:229) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_101]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_101]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_101]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.ForkJoinPool.helpComplete(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[?:1.8.0_101]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[?:1.8.0_101]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_101]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_101]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:1.8.0_101]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.saveHandlerDataToCache(DataCacheHandler.java:228) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler$1.run(DataCacheHandler.java:106) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_101]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]```

**Comment by Rsl1122** [comment]
Thanks for changing the gamemode, it will help me trying to pinpoint the issue.
This issue has been causing trouble for quite some time now (Issues #56 #57 #50 #33 #8 )
What is the worst thing about it is that I don't know what is causing it.
Sometimes Spigot just decides to give null gamemode during GamemodeChangeEvent.
I have tests that caught the issue ( #57 #47), so now I just need to get it fixed.

The uuid was not visible on the webpages because Analysis completely ignores data of players that have missing data.
