### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException on /plan analyze

### ISSUE THREAD

**Issue by zedwick** [Rsl1122/Plan-PlayerAnalytics#64]
**Plan Version:** 2.9.0
**Server Version:** git-Paper-1064
**Database Type:** sqlite
**Command Causing Issue:** /plan analyze

**Description:**
After running the analyze command in-game, I see "Analysis Command timed out!" and the error below in console.

**Steps to Reproduce:**

1. Run ```/plan analyze``` in-game.

**Stack Trace - Console/Errors.txt contents:**
```
[12:57:22 INFO]: Zedwick issued server command: /plan analyze
[12:57:22 WARN]: [Plan] Plugin Plan v2.9.0 generated an exception while executing task 1693
java.lang.ArrayIndexOutOfBoundsException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_45]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_45]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_45]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_45]
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598) ~[?:1.8.0_45]
        at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677) ~[?:1.8.0_45]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735) ~[?:1.8.0_45]
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) ~[?:1.8.0_45]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) ~[?:1.8.0_45]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:1.8.0_45]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_45]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583) ~[?:1.8.0_45]
        at main.java.com.djrapitops.plan.utilities.Analysis.analyzeData(Analysis.java:147) ~[?:?]
        at main.java.com.djrapitops.plan.utilities.Analysis.analyze(Analysis.java:135) ~[?:?]
        at main.java.com.djrapitops.plan.utilities.Analysis$1.run(Analysis.java:67) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1064]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.11.2.jar:git-Paper-1064]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.11.2.jar:git-Paper-1064]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.ArrayIndexOutOfBoundsException
        at java.util.ArrayList.addAll(ArrayList.java:580) ~[?:1.8.0_45]
        at main.java.com.djrapitops.plan.utilities.Analysis.lambda$analyzeData$5(Analysis.java:191) ~[?:?]
        at main.java.com.djrapitops.plan.utilities.Analysis$$Lambda$33/852530624.accept(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_45]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_45]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_45]
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[?:1.8.0_45]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_45]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_45]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_45]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_45]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_45]
```

**Comment by Rsl1122** [comment]
Will be fixed while writing tests for Analysis.
