### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by brooky1010** [Rsl1122/Plan-PlayerAnalytics#66]
**Plan Version: 2.9.0
**Server Version: Spigot 1.11
**Database Type: MySQL
**Description:**
My console:
ERROR Some data might be corrupted: c5ac5699-0510-484f-9945-71746f292fbf
ERROR Caught java.lang.NullPointerException. It has been logged to the Errors.txt 

**Steps to Reproduce:**

1. Nothing. It just happens.

**Stack Trace - Console/Errors.txt contents:**
Errors.txt:
```
[Mar 24 17:23:11] main.java.com.djrapitops.plan.data.cache.GetConsumer Caught java.lang.NullPointerException
[Mar 24 17:23:11]   main.java.com.djrapitops.plan.data.handlers.GamemodeTimesHandler.handleChangeEvent(GamemodeTimesHandler.java:60)
[Mar 24 17:23:11]   main.java.com.djrapitops.plan.data.handlers.GamemodeTimesHandler.handleLogin(GamemodeTimesHandler.java:36)
[Mar 24 17:23:11]   main.java.com.djrapitops.plan.data.listeners.PlanPlayerListener$1$1.process(PlanPlayerListener.java:79)
[Mar 24 17:23:11]   main.java.com.djrapitops.plan.database.databases.SQLDB.giveUserDataToProcessors(SQLDB.java:629)
[Mar 24 17:23:11]   main.java.com.djrapitops.plan.data.cache.GetConsumer.consume(DataCacheGetQueue.java:88)
[Mar 24 17:23:11]   main.java.com.djrapitops.plan.data.cache.GetConsumer.run(DataCacheGetQueue.java:73)
[Mar 24 17:23:11]   java.lang.Thread.run(Thread.java:745)
[Mar 24 17:23:11] 
[Mar 24 17:23:37] main.java.com.djrapitops.plan.utilities.Analysis Caught java.lang.NullPointerException
[Mar 24 17:23:37]   main.java.com.djrapitops.plan.utilities.Analysis.lambda$analyzeData$5(Analysis.java:150)
[Mar 24 17:23:37]   java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[Mar 24 17:23:37]   java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
[Mar 24 17:23:37]   java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
[Mar 24 17:23:37]   java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
[Mar 24 17:23:37]   java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
[Mar 24 17:23:37]   java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[Mar 24 17:23:37]   java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[Mar 24 17:23:37]   java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[Mar 24 17:23:37]   java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[Mar 24 17:23:37] 
[Mar 24 17:23:55] main.java.com.djrapitops.plan.ui.webserver.Response Caught java.lang.NullPointerException
[Mar 24 17:23:55]   main.java.com.djrapitops.plan.utilities.PlaceholderUtils.getInspectReplaceRules(PlaceholderUtils.java:148)
[Mar 24 17:23:55]   main.java.com.djrapitops.plan.ui.DataRequestHandler.getInspectHtml(DataRequestHandler.java:58)
[Mar 24 17:23:55]   main.java.com.djrapitops.plan.ui.webserver.Response.sendStaticResource(Response.java:83)
[Mar 24 17:23:55]   main.java.com.djrapitops.plan.ui.webserver.WebSocketServer$1.run(WebSocketServer.java:77)
[Mar 24 17:23:55]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[Mar 24 17:23:55]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[Mar 24 17:23:55]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[Mar 24 17:23:55]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[Mar 24 17:23:55]   java.lang.Thread.run(Thread.java:745)
[Mar 24 17:23:55] 
[Mar 24 17:23:59] main.java.com.djrapitops.plan.ui.webserver.Response Caught java.lang.NullPointerException
[Mar 24 17:23:59]   main.java.com.djrapitops.plan.utilities.PlaceholderUtils.getInspectReplaceRules(PlaceholderUtils.java:148)
[Mar 24 17:23:59]   main.java.com.djrapitops.plan.ui.DataRequestHandler.getInspectHtml(DataRequestHandler.java:58)
[Mar 24 17:23:59]   main.java.com.djrapitops.plan.ui.webserver.Response.sendStaticResource(Response.java:83)
[Mar 24 17:23:59]   main.java.com.djrapitops.plan.ui.webserver.WebSocketServer$1.run(WebSocketServer.java:77)
[Mar 24 17:23:59]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[Mar 24 17:23:59]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[Mar 24 17:23:59]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[Mar 24 17:23:59]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[Mar 24 17:23:59]   java.lang.Thread.run(Thread.java:745)
[Mar 24 17:23:59]
```
CONSOLE:
```
24.03 17:25:07 [Server] WARN Plugin Plan v2.9.0 generated an exception while executing task 180
24.03 17:25:07 [Server] [Informatie] java.lang.NullPointerException
24.03 17:25:07 [Server] [Informatie] at main.java.com.djrapitops.plan.data.handlers.GamemodeTimesHandler.saveToCache(GamemodeTimesHandler.java:79) ~[?:?]
24.03 17:25:07 [Server] [Informatie] at main.java.com.djrapitops.plan.data.cache.DataCacheHandler$3.process(DataCacheHandler.java:239) ~[?:?]
24.03 17:25:07 [Server] [Informatie] at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.getUserDataForProcessing(DataCacheHandler.java:146) ~[?:?]
24.03 17:25:07 [Server] [Informatie] at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.getUserDataForProcessing(DataCacheHandler.java:159) ~[?:?]
24.03 17:25:07 [Server] [Informatie] at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.saveHandlerDataToCache(DataCacheHandler.java:242) ~[?:?]
24.03 17:25:07 [Server] [Informatie] at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.lambda$saveHandlerDataToCache$1(DataCacheHandler.java:229) ~[?:?]
24.03 17:25:07 [Server] [Informatie] at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_101]
24.03 17:25:07 [Server] [Informatie] at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_101]
24.03 17:25:07 [Server] [Informatie] at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_101]
24.03 17:25:07 [Server] [Informatie] at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_101]
24.03 17:25:07 [Server] [Informatie] at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[?:1.8.0_101]
24.03 17:25:07 [Server] [Informatie] at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_101]
24.03 17:25:07 [Server] [Informatie] at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_101]
24.03 17:25:07 [Server] [Informatie] at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401) ~[?:1.8.0_101]
24.03 17:25:07 [Server] [Informatie] at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) ~[?:1.8.0_101]
24.03 17:25:07 [Server] [Informatie] at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) ~[?:1.8.0_101]
24.03 17:25:07 [Server] [Informatie] at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) ~[?:1.8.0_101]
24.03 17:25:07 [Server] [Informatie] at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:1.8.0_101]
24.03 17:25:07 [Server] [Informatie] at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_101]
24.03 17:25:07 [Server] [Informatie] at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583) ~[?:1.8.0_101]
24.03 17:25:07 [Server] [Informatie] at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.saveHandlerDataToCache(DataCacheHandler.java:228) ~[?:?]
24.03 17:25:07 [Server] [Informatie] at main.java.com.djrapitops.plan.data.cache.DataCacheHandler$1.run(DataCacheHandler.java:106) ~[?:?]
24.03 17:25:07 [Server] [Informatie] at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.jar:git-Spigot-f950f8e-0fa1ad2]
24.03 17:25:07 [Server] [Informatie] at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.11.jar:git-Spigot-f950f8e-0fa1ad2]
24.03 17:25:07 [Server] [Informatie] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
24.03 17:25:07 [Server] [Informatie] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
24.03 17:25:07 [Server] [Informatie] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by Rsl1122** [comment]
Interesting.
Fixed:

- [ ] NPE GamemodeTimesHandler:60
- [ ] NPE GamemodeTimesHandler:79
- [ ] NPE Response / PlaceholderUtils:148
- [ ] NPE Analysis:150
