### ISSUE TITLE
IllegalStateException thrown when queue is full

### ISSUE THREAD

**Issue by OasisMaximus** [Rsl1122/Plan-PlayerAnalytics#67]
Plan Version: 2.8.4
Server Version: Spigot-1.11.2
Database Type: MySQL
Command Causing Issue: none

Description:
At some point when the server starts we get an EntityDeathEvent error from plan, seemingly out of the blue. We removed the plugin because of this because the errors were getting quite excessive. At first they came aroud every 30 seconds, then at some point about every second.
I do not know wether this issue still arises in plan 2.9.0, I have yet to test this. I didn't see any mention of this bug in the bugfixes of 2.9.0, so I still thought I should post. Feel free to close this if you think it's fixed and I'll just get back to you if it still occurs! Thank you by the way for being quick to solve the issue last time!

Steps to Reproduce: Unknown

Proposed Solution: No clue

Stack Trace - Console contents:
The first ever error we got, with a mention of a skeleton:
```[14:04:34] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Plan v2.8.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:394) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.EntityLiving.die(EntityLiving.java:1079) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.EntitySkeletonAbstract.die(EntitySkeletonAbstract.java:120) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.EntitySkeleton.die(EntitySkeleton.java:46) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:933) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.EntityMonster.damageEntity(EntityMonster.java:44) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.Entity.U(Entity.java:383) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.EntityLiving.U(EntityLiving.java:197) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.EntityInsentient.U(EntityInsentient.java:184) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.Entity.A_(Entity.java:312) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1820) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.EntityMonster.A_(EntityMonster.java:28) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1631) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.World.h(World.java:1606) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1432) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:618) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:814) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.IllegalStateException: Queue full
	at java.util.AbstractQueue.add(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.ArrayBlockingQueue.add(Unknown Source) ~[?:1.8.0_101]
	at main.java.com.djrapitops.plan.data.cache.DataCacheGetQueue.scheduleForGet(DataCacheGetQueue.java:46) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.getUserDataForProcessing(DataCacheHandler.java:141) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.getUserDataForProcessing(DataCacheHandler.java:159) ~[?:?]
	at main.java.com.djrapitops.plan.data.listeners.PlanDeathEventListener.onDeath(PlanDeathEventListener.java:52) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor305.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	... 25 more
```

The second ever error we got, with a mention of a zombie:
```
[14:05:00] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Plan v2.8.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:394) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.EntityLiving.die(EntityLiving.java:1079) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.EntityZombie.die(EntityZombie.java:429) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:933) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.EntityMonster.damageEntity(EntityMonster.java:44) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.EntityZombie.damageEntity(EntityZombie.java:163) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.EntityHuman.attack(EntityHuman.java:1023) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.EntityPlayer.attack(EntityPlayer.java:1145) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1569) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.IllegalStateException: Queue full
	at java.util.AbstractQueue.add(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.ArrayBlockingQueue.add(Unknown Source) ~[?:1.8.0_101]
	at main.java.com.djrapitops.plan.data.cache.DataCacheGetQueue.scheduleForGet(DataCacheGetQueue.java:46) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.getUserDataForProcessing(DataCacheHandler.java:141) ~[?:?]
	at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.getUserDataForProcessing(DataCacheHandler.java:159) ~[?:?]
	at main.java.com.djrapitops.plan.data.listeners.PlanDeathEventListener.onDeath(PlanDeathEventListener.java:52) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor305.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
	... 23 more
```

**Comment by Rsl1122** [comment]
This issue is caused because get queue is full, change the GetQueueSize setting to a higher number. 

The queue is used by analysis and all event info processing, so it should be a big number. (default 2000)

I'll try to improve it so that it will open a new overflow queue if a queue is full.

**Comment by Rsl1122** [comment]
Sorry, this issue might have been caused because of my previous tips to fix the issue.

**Comment by OasisMaximus** [comment]
Which setting in the config is the GetQueueSize? There doesn't seem to be one, so I set Cache.Processing.Get-/Save-/Clearlimit to higher values, since I assumed that was the one you meant. I have currently set them to 10000, 2000 and 2000 respectively, and I'm still getting the errors. These aren't in the configuration guide, so I'm not even sure if I should have increased these, should I have decreased these or not have touched them at all?

There are also tons of these in the errors.txt:
```
[Mar 31 18:07:44] main.java.com.djrapitops.plan.data.UserData Caught java.lang.ArrayIndexOutOfBoundsException
```
And quite a few of these:
```
[Mar 31 18:07:45] main.java.com.djrapitops.plan.utilities.Analysis Caught java.lang.NullPointerException
[Mar 31 18:07:45]   main.java.com.djrapitops.plan.utilities.Analysis.lambda$analyzeData$5(Analysis.java:150)
[Mar 31 18:07:45]   java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[Mar 31 18:07:45]   java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
[Mar 31 18:07:45]   java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[Mar 31 18:07:45]   java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
[Mar 31 18:07:45]   java.util.concurrent.CountedCompleter.exec(Unknown Source)
[Mar 31 18:07:45]   java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[Mar 31 18:07:45]   java.util.concurrent.ForkJoinPool.helpComplete(Unknown Source)
[Mar 31 18:07:45]   java.util.concurrent.ForkJoinPool.externalHelpComplete(Unknown Source)
[Mar 31 18:07:45]   java.util.concurrent.ForkJoinTask.externalAwaitDone(Unknown Source)
[Mar 31 18:07:45]   java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
[Mar 31 18:07:45]   java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
[Mar 31 18:07:45]   java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
[Mar 31 18:07:45]   java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
[Mar 31 18:07:45]   java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[Mar 31 18:07:45]   java.util.stream.ReferencePipeline.forEach(Unknown Source)
[Mar 31 18:07:45]   java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
[Mar 31 18:07:45]   main.java.com.djrapitops.plan.utilities.Analysis.analyzeData(Analysis.java:147)
[Mar 31 18:07:45]   main.java.com.djrapitops.plan.utilities.Analysis.analyze(Analysis.java:135)
[Mar 31 18:07:45]   main.java.com.djrapitops.plan.utilities.Analysis$1.run(Analysis.java:67)
[Mar 31 18:07:45]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[Mar 31 18:07:45]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[Mar 31 18:07:45]   java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[Mar 31 18:07:45]   java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[Mar 31 18:07:45]   java.lang.Thread.run(Unknown Source)
```
My config:
```
# Plan Config | More info at https://www.spigotmc.org/wiki/plan-configuration/
Settings:
  Locale: default
  UseTextUI: false
  Data:
    GatherLocations: true
  Analysis:
    LogProgressOnConsole: false
    MinutesPlayedUntilConsidiredActive: 15
  Cache:
    Processing:
      GetLimit: 10000
      SaveLimit: 2000
      ClearLimit: 2000
    AnalysisCache:
      RefreshAnalysisCacheOnEnable: false
      RefreshEveryXMinutes: -1
    InspectCache:
      ClearFromInspectCacheAfterXMinutes: 2
    DataCache:
      SaveEveryXMinutes: 0.5
      ClearCacheEveryXSaves: 1
  WebServer:
    Enabled: true
    Port: 8804
    ShowAlternativeServerIP: true
    AlternativeIP: oasis-mc.us:%port%
    Security:
      DisplayIPsAndUUIDs: true
      AddressSecurityCode: s1sa0asdf
Customization:
  Colors:
    Commands:
      Main: '&2'
      Secondary: '&7'
      Highlight: '&f'
    HTML:
      ActivityGraph:
        OnlinePlayers: 1E90FF
        OnlinePlayersFill: 75BBFF
        NewPlayers: 228B22
      GamemodePie:
        Survival: '951800'
        Creative: 01A1DB
        Adventure: '769316'
        Spectator: 228B22
      ActivityPie:
        Active: 228B22
        Banned: '951800'
        Inactive: A9A9A9
        JoinedOnce: '808080'
      GenderPie:
        Female: ED97E3
        Male: 7CB9D6
        Unknown: A9A9A9
  DemographicsTriggers:
    Trigger: i'm, am, im, bin
    Female: female, girl, gurl, woman, gal, mrs, she, miss, feminin, weiblich, mädchen, frau
    Male: male, boy, man, boe, sir, mr, guy, he, männlich, maskulin, junge, mann
    IgnoreWhen: sure, think, with, are, you, din
database:
  type: mysql
mysql:
  host: localhost
  port: 3306
  user: PlanPlayerStats
  password: 0as1spl4n
  database: planstatistics
```

**Comment by Rsl1122** [comment]
Could you please send me the full contents of the Errors.txt. 
The Settings.Processing.GetLimit is the correct setting. 
Did you update to 2.9.1?

**Comment by Rsl1122** [comment]
I checked, and only thing that logs exceptions in UserData to the Errors.txt is this:
```
try {
            isBanned = player.isBanned();
        } catch (Exception e) {
            Plan plugin = getPlugin(Plan.class);
            plugin.logError("Error getting ban date from Bukkit files. " + uuid.toString());
            plugin.toLog(this.getClass().getName(), e);
            isBanned = false;
        }
```
player.isBanned() is a bukkit method and the error is caused by code in Spigot/Minecraft Server/Bukkit code first encountered here: #35
