### ISSUE TITLE
Unspecified issue trying to access webpage

### ISSUE THREAD

**Issue by Nikolay0054** [Rsl1122/Plan-PlayerAnalytics#71]
**Plan Version:** 2.9.1
**Server Version:** Spigot-1.11.2
**Database Type:** MySQL
**Command Causing Issue:**

**Description:**
Doesn't work player analitycs
**Steps to Reproduce:**
1. Use Essentials Chat
2. Set prefix to user

**Proposed Solution:**

**Stack Trace - Console/Errors.txt contents:**
```
404 Data was not found in cache
```
in database nick looks like:
```
§0(§5????????§0)§7 Nikolay0054§r
```
("?" is a cyrillic letters)

**Comment by Rsl1122** [comment]
Hello, did you use /plan inspect <playername> to access the link?
The data needs to be cached before it can be viewed, the command does that.

Does the command time out?
If the command times out, please paste the contents of Errors.txt and the latest log here.

**Comment by Nikolay0054** [comment]
/plan inspect Nikolay0054
`[Plan] This Player has not played on this server.`

**Comment by Nikolay0054** [comment]
There is still problem

**Comment by Rsl1122** [comment]
Could you please give me more to work with. Please paste the whole contents of Errors.txt in the /plugins/Plan folder.

**Comment by Nikolay0054** [comment]
[Here](https://factmodule.ru/videos/video.mp4)
I don't have Errors.txt in the /plugins/Plan folder
And i'm now on PaperSpigot 1078
```
[14:06:54 ERROR]: Command Dispatched Async: tellraw Nikolay0054 ["",{"text":"Click Me","underlined":true,"clickEvent":{"action":"open_url","value":"http://factmodule.ru/stat/bAkEd/player/Nikolay0054"}}]
[14:06:54 ERROR]: Please notify author of plugin causing this execution to fix this bug! see: http://bit.ly/1oSiM6C
java.lang.Throwable
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:657) [patched_1.11.2.jar:git-Paper-1078]
        at main.java.com.djrapitops.plan.command.commands.SearchCommand$1.run(SearchCommand.java:106) [Plan.2.9.3.jar:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.11.2.jar:git-Paper-1078]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.11.2.jar:git-Paper-1078]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.11.2.jar:git-Paper-1078]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by Nikolay0054** [comment]
Yeah, i'm got it. This is because my server has online mode false. Please, add support for pirated servers

**Comment by Rsl1122** [comment]
The plugin uses UUID for saving, and pretty much everything related to how the data is handled. 
Thus adding support for pirated clients would require a full rewrite. 
I don't have enough time to rewrite the plugin, since I have to ensure the current functionality as it currently stands - by writing tests for the current code.
I have split the other issue into a new issue.
