### ISSUE TITLE
ConcurrentModificationException on player connect

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#715]
Spigot 1.13 latest
Plan 4.4.5

When player connected:
```
[18:29:55 WARN]: [Plan] Plugin Plan v4.4.5 generated an exception while executing task 70
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361) ~[?:1.8.0_181]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_181]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[?:1.8.0_181]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:1.8.0_181]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_181]
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_181]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_181]
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:1.8.0_181]
        at com.djrapitops.plugin.api.systems.TaskCenter.taskCancelled(TaskCenter.java:56) ~[?:?]
        at com.djrapitops.plugin.task.bukkit.AbsBukkitRunnable.cancel(AbsBukkitRunnable.java:87) ~[?:?]
        at com.djrapitops.plugin.task.AbsRunnable.cancel(AbsRunnable.java:51) ~[?:?]
        at com.djrapitops.plan.system.tasks.LogsFolderCleanTask.run(LogsFolderCleanTask.java:37) ~[?:?]
        at com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:39) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.jar-2018-08-25-2137:git-Spigot-fe3ab0d-162bda9]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by Rsl1122** [comment]
Looks like it was unfortunate collision with the exact moment logs folder clean task finished

**Comment by SlimeDog** [comment]
No worries. Just wanted to let you know.
