### ISSUE TITLE
Update check disable

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#751]
Spigot 1.13.1 latest
Plan 4.4.7-b1 aka 4.5.0-DEV1

In my config.yml:
```
Plugin:
    Allow-Update-Command: false
```
which is no longer present in 4.4.7-b1 config.yml (it was last seen in 4.4.7 config.yml and bungeeconfig.yml) and is no longer observed. The update check was intercepted by my network filters. Is there no longer an option to disable update checks? I have my own automagical update checker.
```
Sat Oct 13 09:47:42 PDT 2018: Intercepted outgoing connection to host 'raw.githubusercontent.com'
        at com.djrapitops.plan.system.update.VersionInfoLoader.load(VersionInfoLoader.java:34)
        at com.djrapitops.plan.system.update.VersionCheckSystem.enable(VersionCheckSystem.java:58)
        at com.djrapitops.plan.system.PlanSystem.enableSystems(PlanSystem.java:121)
        at com.djrapitops.plan.system.PlanSystem.enable(PlanSystem.java:101)
        at com.djrapitops.plan.Plan.onEnable(Plan.java:55)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431)
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345)
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584)
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546)
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424)
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702)
        at java.lang.Thread.run(Thread.java:748)
Sat Oct 13 09:47:42 PDT 2018: Blocked connection to host 'raw.githubusercontent.com'
Sat Oct 13 09:47:42 PDT 2018: Intercepted outgoing connection to host 'raw.githubusercontent.com'
        at com.djrapitops.plan.system.update.VersionInfoLoader.load(VersionInfoLoader.java:34)
        at com.djrapitops.plan.system.update.VersionCheckSystem.enable(VersionCheckSystem.java:58)
        at com.djrapitops.plan.system.PlanSystem.enableSystems(PlanSystem.java:121)
        at com.djrapitops.plan.system.PlanSystem.enable(PlanSystem.java:101)
        at com.djrapitops.plan.Plan.onEnable(Plan.java:55)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431)
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345)
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584)
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546)
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424)
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702)
        at java.lang.Thread.run(Thread.java:748)
Sat Oct 13 09:47:42 PDT 2018: Blocked connection to host 'raw.githubusercontent.com'
Sat Oct 13 09:47:42 PDT 2018: Intercepted outgoing connection to host '0:0:0:0:0:0:0:0'
        at sun.nio.ch.Net.getRevealedLocalAddress(Net.java:175)
        at sun.nio.ch.ServerSocketAdaptor.getInetAddress(ServerSocketAdaptor.java:83)
        at java.net.ServerSocket.getLocalSocketAddress(ServerSocket.java:476)
        at sun.net.httpserver.ServerImpl$1.run(ServerImpl.java:254)
        at sun.net.httpserver.ServerImpl$1.run(ServerImpl.java:250)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.httpserver.ServerImpl.getAddress(ServerImpl.java:249)
        at sun.net.httpserver.HttpServerImpl.getAddress(HttpServerImpl.java:90)
        at com.djrapitops.plan.system.webserver.WebServer.initServer(WebServer.java:132)
        at com.djrapitops.plan.system.webserver.WebServer.enable(WebServer.java:82)
        at com.djrapitops.plan.system.webserver.WebServerSystem.enable(WebServerSystem.java:35)
        at com.djrapitops.plan.system.PlanSystem.enableSystems(PlanSystem.java:121)
        at com.djrapitops.plan.system.PlanSystem.enable(PlanSystem.java:101)
        at com.djrapitops.plan.Plan.onEnable(Plan.java:55)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431)
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345)
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584)
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546)
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424)
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by Rsl1122** [comment]
Looks like it was removed during the rework.

### Prior 4.5.0

In 4.4.7 this setting was used in an if-else block, so there has not been an option to disable the update check completely in previous versions.

```
if (Settings.ALLOW_UPDATE.isTrue()) {
   // Check from github versions.txt
} else {
   // Check using old methods, from github plugin.yml and spigot
}
```

### Reason for removal

Since the old version check system (that checked from spigot) was removed/deprecated, the need for the if else block vanished and thus the setting was also removed. 
The setting was also related to #539 (Update command) that was scrapped (Reasons in the issue).

### Moving forward

In 4.5.0 the version update notification will be moved to the website instead of in-game chat to be less intrusive about updates.
I'll add this config setting though.

**Comment by SlimeDog** [comment]
Excellent.
