### ISSUE TITLE
ArrayIndexOutOfBoundsException: Index 339 out of bounds for length 339

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#755]
Plan 4.5.0 DEV2

```
| 10-15 21:00:38 | com.djrapitops.plan.system.processing.Processing caught ArrayIndexOutOfBoundsException
| 10-15 21:00:38 | java.lang.ArrayIndexOutOfBoundsException: Index 339 out of bounds for length 339
| 10-15 21:00:38 |    java.base/java.util.ArrayDeque.grow(ArrayDeque.java:159)
| 10-15 21:00:38 |    java.base/java.util.ArrayDeque.addLast(ArrayDeque.java:308)
| 10-15 21:00:38 |    java.base/java.util.ArrayDeque.add(ArrayDeque.java:495)
| 10-15 21:00:38 |    com.djrapitops.plugin.utilities.EjectingQueue.add(EjectingQueue.java:42)
| 10-15 21:00:38 |    com.djrapitops.plugin.logging.debug.MemoryDebugLogger.logOn(MemoryDebugLogger.java:32)
| 10-15 21:00:38 |    com.djrapitops.plugin.logging.debug.CombineDebugLogger.logOn(CombineDebugLogger.java:26)
| 10-15 21:00:38 |    com.djrapitops.plugin.benchmarking.Timings.lambda$end$0(Timings.java:74)
| 10-15 21:00:38 |    java.base/java.util.Optional.ifPresent(Optional.java:183)
| 10-15 21:00:38 |    com.djrapitops.plugin.benchmarking.Timings.end(Timings.java:74)
| 10-15 21:00:38 |    com.djrapitops.plan.system.database.databases.sql.processing.AbstractSQLStatement.stopBenchmark(AbstractSQLStatement.java:37)
| 10-15 21:00:38 |    com.djrapitops.plan.system.database.databases.sql.processing.ExecStatement.execute(ExecStatement.java:28)
| 10-15 21:00:38 |    com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:280)
| 10-15 21:00:38 |    com.djrapitops.plan.system.database.databases.sql.tables.Table.execute(Table.java:153)
| 10-15 21:00:38 |    com.djrapitops.plan.system.database.databases.sql.tables.PingTable.insertPing(PingTable.java:71)
| 10-15 21:00:38 |    com.djrapitops.plan.system.database.databases.sql.operation.SQLSaveOps.ping(SQLSaveOps.java:136)
| 10-15 21:00:38 |    com.djrapitops.plan.system.processing.processors.player.PingInsertProcessor.run(PingInsertProcessor.java:64)
| 10-15 21:00:38 |    com.djrapitops.plan.system.processing.Processing.lambda$submitCritical$1(Processing.java:61)
| 10-15 21:00:38 |    java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
| 10-15 21:00:38 |    java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
| 10-15 21:00:38 |    java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
| 10-15 21:00:38 |    java.base/java.lang.Thread.run(Thread.java:834)
| 10-15 21:00:39 | com.djrapitops.plan.system.processing.Processing caught ArrayIndexOutOfBoundsException
| 10-15 21:00:39 | java.lang.ArrayIndexOutOfBoundsException: Index 342 out of bounds for length 339
| 10-15 21:00:39 |    java.base/java.util.ArrayDeque.elementAt(ArrayDeque.java:260)
| 10-15 21:00:39 |    java.base/java.util.ArrayDeque.pollFirst(ArrayDeque.java:380)
| 10-15 21:00:39 |    java.base/java.util.ArrayDeque.poll(ArrayDeque.java:538)
| 10-15 21:00:39 |    com.djrapitops.plugin.utilities.EjectingQueue.add(EjectingQueue.java:39)
| 10-15 21:00:39 |    com.djrapitops.plugin.logging.debug.MemoryDebugLogger.logOn(MemoryDebugLogger.java:32)
| 10-15 21:00:39 |    com.djrapitops.plugin.logging.debug.CombineDebugLogger.logOn(CombineDebugLogger.java:26)
| 10-15 21:00:39 |    com.djrapitops.plugin.benchmarking.Timings.lambda$end$0(Timings.java:74)
| 10-15 21:00:39 |    java.base/java.util.Optional.ifPresent(Optional.java:183)
| 10-15 21:00:39 |    com.djrapitops.plugin.benchmarking.Timings.end(Timings.java:74)
| 10-15 21:00:39 |    com.djrapitops.plan.system.database.databases.sql.processing.AbstractSQLStatement.stopBenchmark(AbstractSQLStatement.java:37)
| 10-15 21:00:39 |    com.djrapitops.plan.system.database.databases.sql.processing.ExecStatement.execute(ExecStatement.java:28)
| 10-15 21:00:39 |    com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:280)
| 10-15 21:00:39 |    com.djrapitops.plan.system.database.databases.sql.tables.Table.execute(Table.java:153)
| 10-15 21:00:39 |    com.djrapitops.plan.system.database.databases.sql.tables.CommandUseTable.commandUsed(CommandUseTable.java:109)
| 10-15 21:00:39 |    com.djrapitops.plan.system.database.databases.sql.operation.SQLSaveOps.commandUsed(SQLSaveOps.java:111)
| 10-15 21:00:39 |    com.djrapitops.plan.system.processing.processors.CommandProcessor.run(CommandProcessor.java:28)
| 10-15 21:00:39 |    com.djrapitops.plan.system.processing.Processing.lambda$submitCritical$1(Processing.java:61)
| 10-15 21:00:39 |    java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
| 10-15 21:00:39 |    java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
| 10-15 21:00:39 |    java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
| 10-15 21:00:39 |    java.base/java.lang.Thread.run(Thread.java:834)
| 10-15 21:00:41 | com.djrapitops.plan.system.processing.Processing caught ArrayIndexOutOfBoundsException
| 10-15 21:00:41 | java.lang.ArrayIndexOutOfBoundsException: Index 342 out of bounds for length 339
| 10-15 21:00:41 |    java.base/java.util.ArrayDeque.elementAt(ArrayDeque.java:260)
| 10-15 21:00:41 |    java.base/java.util.ArrayDeque.pollFirst(ArrayDeque.java:380)
| 10-15 21:00:41 |    java.base/java.util.ArrayDeque.poll(ArrayDeque.java:538)
| 10-15 21:00:41 |    com.djrapitops.plugin.utilities.EjectingQueue.add(EjectingQueue.java:39)
| 10-15 21:00:41 |    com.djrapitops.plugin.logging.debug.MemoryDebugLogger.logOn(MemoryDebugLogger.java:32)
| 10-15 21:00:41 |    com.djrapitops.plugin.logging.debug.CombineDebugLogger.logOn(CombineDebugLogger.java:26)
| 10-15 21:00:41 |    com.djrapitops.plugin.benchmarking.Timings.lambda$end$0(Timings.java:74)
| 10-15 21:00:41 |    java.base/java.util.Optional.ifPresent(Optional.java:183)
| 10-15 21:00:41 |    com.djrapitops.plugin.benchmarking.Timings.end(Timings.java:74)
| 10-15 21:00:41 |    com.djrapitops.plan.system.database.databases.sql.processing.AbstractSQLStatement.stopBenchmark(AbstractSQLStatement.java:37)
| 10-15 21:00:41 |    com.djrapitops.plan.system.database.databases.sql.processing.ExecStatement.execute(ExecStatement.java:28)
| 10-15 21:00:41 |    com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:280)
| 10-15 21:00:41 |    com.djrapitops.plan.system.database.databases.sql.tables.Table.execute(Table.java:153)
| 10-15 21:00:41 |    com.djrapitops.plan.system.database.databases.sql.tables.PingTable.insertPing(PingTable.java:71)
| 10-15 21:00:41 |    com.djrapitops.plan.system.database.databases.sql.operation.SQLSaveOps.ping(SQLSaveOps.java:136)
| 10-15 21:00:41 |    com.djrapitops.plan.system.processing.processors.player.PingInsertProcessor.run(PingInsertProcessor.java:64)
| 10-15 21:00:41 |    com.djrapitops.plan.system.processing.Processing.lambda$submitCritical$1(Processing.java:61)
| 10-15 21:00:41 |    java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
| 10-15 21:00:41 |    java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
| 10-15 21:00:41 |    java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
| 10-15 21:00:41 |    java.base/java.lang.Thread.run(Thread.java:834)
| 10-15 21:00:43 | com.djrapitops.plan.system.processing.Processing caught ArrayIndexOutOfBoundsException
| 10-15 21:00:43 | java.lang.ArrayIndexOutOfBoundsException: Index 342 out of bounds for length 339
| 10-15 21:00:43 |    java.base/java.util.ArrayDeque.elementAt(ArrayDeque.java:260)
| 10-15 21:00:43 |    java.base/java.util.ArrayDeque.pollFirst(ArrayDeque.java:380)
| 10-15 21:00:43 |    java.base/java.util.ArrayDeque.poll(ArrayDeque.java:538)
| 10-15 21:00:43 |    com.djrapitops.plugin.utilities.EjectingQueue.add(EjectingQueue.java:39)
| 10-15 21:00:43 |    com.djrapitops.plugin.logging.debug.MemoryDebugLogger.logOn(MemoryDebugLogger.java:32)
| 10-15 21:00:43 |    com.djrapitops.plugin.logging.debug.CombineDebugLogger.logOn(CombineDebugLogger.java:26)
| 10-15 21:00:43 |    com.djrapitops.plugin.benchmarking.Timings.lambda$end$0(Timings.java:74)
| 10-15 21:00:43 |    java.base/java.util.Optional.ifPresent(Optional.java:183)
| 10-15 21:00:43 |    com.djrapitops.plugin.benchmarking.Timings.end(Timings.java:74)
| 10-15 21:00:43 |    com.djrapitops.plan.system.database.databases.sql.processing.AbstractSQLStatement.stopBenchmark(AbstractSQLStatement.java:37)
| 10-15 21:00:43 |    com.djrapitops.plan.system.database.databases.sql.processing.ExecStatement.execute(ExecStatement.java:28)
| 10-15 21:00:43 |    com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:280)
| 10-15 21:00:43 |    com.djrapitops.plan.system.database.databases.sql.tables.Table.execute(Table.java:153)
| 10-15 21:00:43 |    com.djrapitops.plan.system.database.databases.sql.tables.CommandUseTable.commandUsed(CommandUseTable.java:109)
| 10-15 21:00:43 |    com.djrapitops.plan.system.database.databases.sql.operation.SQLSaveOps.commandUsed(SQLSaveOps.java:111)
| 10-15 21:00:43 |    com.djrapitops.plan.system.processing.processors.CommandProcessor.run(CommandProcessor.java:28)
| 10-15 21:00:43 |    com.djrapitops.plan.system.processing.Processing.lambda$submitCritical$1(Processing.java:61)
| 10-15 21:00:43 |    java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
| 10-15 21:00:43 |    java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
| 10-15 21:00:43 |    java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
| 10-15 21:00:43 |    java.base/java.lang.Thread.run(Thread.java:834)
| 10-15 21:00:44 | com.djrapitops.plan.system.processing.Processing caught ArrayIndexOutOfBoundsException
| 10-15 21:00:44 | java.lang.ArrayIndexOutOfBoundsException: Index 342 out of bounds for length 339
| 10-15 21:00:44 |    java.base/java.util.ArrayDeque.elementAt(ArrayDeque.java:260)
| 10-15 21:00:44 |    java.base/java.util.ArrayDeque.pollFirst(ArrayDeque.java:380)
| 10-15 21:00:44 |    java.base/java.util.ArrayDeque.poll(ArrayDeque.java:538)
| 10-15 21:00:44 |    com.djrapitops.plugin.utilities.EjectingQueue.add(EjectingQueue.java:39)
| 10-15 21:00:44 |    com.djrapitops.plugin.logging.debug.MemoryDebugLogger.logOn(MemoryDebugLogger.java:32)
| 10-15 21:00:44 |    com.djrapitops.plugin.logging.debug.CombineDebugLogger.logOn(CombineDebugLogger.java:26)
| 10-15 21:00:44 |    com.djrapitops.plugin.benchmarking.Timings.lambda$end$0(Timings.java:74)
| 10-15 21:00:44 |    java.base/java.util.Optional.ifPresent(Optional.java:183)
| 10-15 21:00:44 |    com.djrapitops.plugin.benchmarking.Timings.end(Timings.java:74)
| 10-15 21:00:44 |    com.djrapitops.plan.system.database.databases.sql.processing.AbstractSQLStatement.stopBenchmark(AbstractSQLStatement.java:37)
| 10-15 21:00:44 |    com.djrapitops.plan.system.database.databases.sql.processing.ExecStatement.execute(ExecStatement.java:28)
| 10-15 21:00:44 |    com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:280)
| 10-15 21:00:44 |    com.djrapitops.plan.system.database.databases.sql.tables.Table.execute(Table.java:153)
| 10-15 21:00:44 |    com.djrapitops.plan.system.database.databases.sql.tables.PingTable.insertPing(PingTable.java:71)
| 10-15 21:00:44 |    com.djrapitops.plan.system.database.databases.sql.operation.SQLSaveOps.ping(SQLSaveOps.java:136)
| 10-15 21:00:44 |    com.djrapitops.plan.system.processing.processors.player.PingInsertProcessor.run(PingInsertProcessor.java:64)
| 10-15 21:00:44 |    com.djrapitops.plan.system.processing.Processing.lambda$submitCritical$1(Processing.java:61)
| 10-15 21:00:44 |    java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
| 10-15 21:00:44 |    java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
| 10-15 21:00:44 |    java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
| 10-15 21:00:44 |    java.base/java.lang.Thread.run(Thread.java:834)
| 10-15 21:00:50 | com.djrapitops.plan.system.processing.Processing caught ArrayIndexOutOfBoundsException
| 10-15 21:00:50 | java.lang.ArrayIndexOutOfBoundsException: Index 342 out of bounds for length 339
| 10-15 21:00:50 |    java.base/java.util.ArrayDeque.elementAt(ArrayDeque.java:260)
| 10-15 21:00:50 |    java.base/java.util.ArrayDeque.pollFirst(ArrayDeque.java:380)
| 10-15 21:00:50 |    java.base/java.util.ArrayDeque.poll(ArrayDeque.java:538)
| 10-15 21:00:50 |    com.djrapitops.plugin.utilities.EjectingQueue.add(EjectingQueue.java:39)
| 10-15 21:00:50 |    com.djrapitops.plugin.logging.debug.MemoryDebugLogger.logOn(MemoryDebugLogger.java:32)
| 10-15 21:00:50 |    com.djrapitops.plugin.logging.debug.CombineDebugLogger.logOn(CombineDebugLogger.java:26)
| 10-15 21:00:50 |    com.djrapitops.plugin.benchmarking.Timings.lambda$end$0(Timings.java:74)
| 10-15 21:00:50 |    java.base/java.util.Optional.ifPresent(Optional.java:183)
| 10-15 21:00:50 |    com.djrapitops.plugin.benchmarking.Timings.end(Timings.java:74)
| 10-15 21:00:50 |    com.djrapitops.plan.system.database.databases.sql.processing.AbstractSQLStatement.stopBenchmark(AbstractSQLStatement.java:37)
| 10-15 21:00:50 |    com.djrapitops.plan.system.database.databases.sql.processing.ExecStatement.execute(ExecStatement.java:28)
| 10-15 21:00:50 |    com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:280)
| 10-15 21:00:50 |    com.djrapitops.plan.system.database.databases.sql.tables.Table.execute(Table.java:153)
| 10-15 21:00:50 |    com.djrapitops.plan.system.database.databases.sql.tables.PingTable.insertPing(PingTable.java:71)
| 10-15 21:00:50 |    com.djrapitops.plan.system.database.databases.sql.operation.SQLSaveOps.ping(SQLSaveOps.java:136)
| 10-15 21:00:50 |    com.djrapitops.plan.system.processing.processors.player.PingInsertProcessor.run(PingInsertProcessor.java:64)
| 10-15 21:00:50 |    com.djrapitops.plan.system.processing.Processing.lambda$submitCritical$1(Processing.java:61)
| 10-15 21:00:50 |    java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
| 10-15 21:00:50 |    java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
| 10-15 21:00:50 |    java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
| 10-15 21:00:50 |    java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Rsl1122** [comment]
I have opened another issue to AbstractPluginFramework (Above this comment).

Thanks for reporting this.

**Comment by mibby** [comment]
@Rsl1122 Do you have any estimate when the next dev build will be published with this fix?

Plan just continuously spams the error. :(

```
[01:43:02] [Plan Critical-pool-1/ERROR]: [Plan] Error was caught by com.djrapitops.plan.system.processing.Processing
java.lang.ArrayIndexOutOfBoundsException: Index 2571 out of bounds for length 2571
	at java.util.ArrayDeque.grow(ArrayDeque.java:159) ~[?:?]
	at java.util.ArrayDeque.addLast(ArrayDeque.java:308) ~[?:?]
	at java.util.ArrayDeque.add(ArrayDeque.java:495) ~[?:?]
	at com.djrapitops.plugin.utilities.EjectingQueue.add(EjectingQueue.java:42) ~[?:?]
	at com.djrapitops.plugin.logging.debug.MemoryDebugLogger.logOn(MemoryDebugLogger.java:32) ~[?:?]
	at com.djrapitops.plugin.logging.debug.CombineDebugLogger.logOn(CombineDebugLogger.java:26) ~[?:?]
	at com.djrapitops.plugin.benchmarking.Timings.lambda$end$0(Timings.java:74) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.djrapitops.plugin.benchmarking.Timings.end(Timings.java:74) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.processing.AbstractSQLStatement.stopBenchmark(AbstractSQLStatement.java:37) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.processing.ExecStatement.execute(ExecStatement.java:28) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:280) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.tables.Table.execute(Table.java:153) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.tables.PingTable.insertPing(PingTable.java:71) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.operation.SQLSaveOps.ping(SQLSaveOps.java:136) ~[?:?]
	at com.djrapitops.plan.system.processing.processors.player.PingInsertProcessor.run(PingInsertProcessor.java:64) ~[?:?]
	at com.djrapitops.plan.system.processing.Processing.lambda$submitCritical$1(Processing.java:61) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[01:43:24] [Plan Critical-pool-0/ERROR]: [Plan] Error was caught by com.djrapitops.plan.system.processing.Processing
java.lang.ArrayIndexOutOfBoundsException: Index 2700 out of bounds for length 2571
	at java.util.ArrayDeque.elementAt(ArrayDeque.java:260) ~[?:?]
	at java.util.ArrayDeque.pollFirst(ArrayDeque.java:380) ~[?:?]
	at java.util.ArrayDeque.poll(ArrayDeque.java:538) ~[?:?]
	at com.djrapitops.plugin.utilities.EjectingQueue.add(EjectingQueue.java:39) ~[?:?]
	at com.djrapitops.plugin.logging.debug.MemoryDebugLogger.logOn(MemoryDebugLogger.java:32) ~[?:?]
	at com.djrapitops.plugin.logging.debug.CombineDebugLogger.logOn(CombineDebugLogger.java:26) ~[?:?]
	at com.djrapitops.plugin.benchmarking.Timings.lambda$end$0(Timings.java:74) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.djrapitops.plugin.benchmarking.Timings.end(Timings.java:74) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.processing.AbstractSQLStatement.stopBenchmark(AbstractSQLStatement.java:37) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.processing.ExecStatement.execute(ExecStatement.java:28) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:280) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.tables.Table.execute(Table.java:153) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.tables.PingTable.insertPing(PingTable.java:71) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.operation.SQLSaveOps.ping(SQLSaveOps.java:136) ~[?:?]
	at com.djrapitops.plan.system.processing.processors.player.PingInsertProcessor.run(PingInsertProcessor.java:64) ~[?:?]
	at com.djrapitops.plan.system.processing.Processing.lambda$submitCritical$1(Processing.java:61) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

As well as occasionally throws this one out too.

```
[03:01:08] [Craft Scheduler Thread - 804/WARN]: [Plan] Error was caught by com.djrapitops.plan.system.tasks.server.PeriodicAnalysisTask
com.djrapitops.plan.api.exceptions.connection.InternalErrorException: Analysis failed due to exception
	at com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.analyseAndGetHtml(GenerateAnalysisPageRequest.java:103) ~[?:?]
	at com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.generateAndCache(GenerateAnalysisPageRequest.java:85) ~[?:?]
	at com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.handleRequest(GenerateAnalysisPageRequest.java:78) ~[?:?]
	at com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.runLocally(GenerateAnalysisPageRequest.java:94) ~[?:?]
	at com.djrapitops.plan.system.info.ServerInfoSystem.runLocally(ServerInfoSystem.java:50) ~[?:?]
	at com.djrapitops.plan.system.info.InfoSystem.sendRequest(InfoSystem.java:110) ~[?:?]
	at com.djrapitops.plan.system.tasks.server.PeriodicAnalysisTask.lambda$run$0(PeriodicAnalysisTask.java:45) ~[?:?]
	at com.djrapitops.plan.system.info.connection.WebExceptionLogger.logIfOccurs(WebExceptionLogger.java:45) ~[?:?]
	at com.djrapitops.plan.system.tasks.server.PeriodicAnalysisTask.run(PeriodicAnalysisTask.java:44) ~[?:?]
	at com.djrapitops.plugin.task.bukkit.BukkitRunnableFactory$1.run(BukkitRunnableFactory.java:32) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.1.jar:git-Paper-373]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.1.jar:git-Paper-373]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
[03:01:12] [Plan Critical-pool-0/ERROR]: [Plan] Error was caught by com.djrapitops.plan.system.processing.Processing
java.lang.ArrayIndexOutOfBoundsException: null
```

**Comment by Rsl1122** [comment]
Monday
