### ISSUE TITLE
Exception: Apparent connection leak detected

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#756]
Abstract-Plugin-Framework compiled as of commit https://github.com/Rsl1122/Abstract-Plugin-Framework/commit/e843deeaed194dadac1b0dfface6c7d37fab0b99
Plan compiled as of commit https://github.com/Rsl1122/Plan-PlayerAnalytics/commit/ca01c26a19d242d849f0269d4e0ca3a7664c0235

Compiled both APF and Plan early to hopefully resolve issue https://github.com/Rsl1122/Plan-PlayerAnalytics/issues/755 spamming console errors. Now running into this error.
```
[02:23:01] [Plan Connection Pool-1 housekeeper/WARN]: [plan.com.zaxxer.hikari.pool.ProxyLeakTask] Connection leak detection triggered for com.mysql.jdbc.JDBC4Connection@342f1861 on thread Server thread, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at plan.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.MySQLDB.getConnection(MySQLDB.java:104) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.MySQLDB.setupDataSource(MySQLDB.java:96) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.SQLDB.init(SQLDB.java:140) ~[?:?]
	at com.djrapitops.plan.system.database.DBSystem.enable(DBSystem.java:89) ~[?:?]
	at com.djrapitops.plan.system.database.BukkitDBSystem.enable(BukkitDBSystem.java:51) ~[?:?]
	at com.djrapitops.plan.system.PlanSystem.enableSystems(PlanSystem.java:121) ~[?:?]
	at com.djrapitops.plan.system.PlanSystem.enable(PlanSystem.java:101) ~[?:?]
	at com.djrapitops.plan.Plan.onEnable(Plan.java:55) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.13.1.jar:git-Paper-385]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.1.jar:git-Paper-385]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.1.jar:git-Paper-385]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:438) ~[patched_1.13.1.jar:git-Paper-385]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:352) ~[patched_1.13.1.jar:git-Paper-385]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.1.jar:git-Paper-385]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[patched_1.13.1.jar:git-Paper-385]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.1.jar:git-Paper-385]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.1.jar:git-Paper-385]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.1.jar:git-Paper-385]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Rsl1122** [comment]
Imma see if it runs into this when I compile later today

**Comment by mibby** [comment]
I have not been able to reproduce with dev 4 so I assume it has been fixed. :)
