### ISSUE TITLE
ViaVersion 1.6.0 + Plan 4.5.0 = Players can't connect to game server

### ISSUE THREAD

**Issue by runelynx** [Rsl1122/Plan-PlayerAnalytics#768]
### Describe the bug
Players cannot connect to the server (via bungee) when Plan 4.5.0 & ViaVersion 1.6.0 (both are latest) are installed at the same time. 

Rolling back to Plan 4.4.7 solves the issue, but also results in ViaVersion 1.4.1 being used---note that I only have ViaVersion 1.6.0 in the plugins folder.  This tells me you are shading an older version of ViaVersion perhaps? 

Either way -- please fix? 

~~~~~~~~~~~~~~~~~~~


[23:26:30] [INFO]: [BungeePerms] Login by PBunnny (84670640-eb98-4b5b-a3da-7e7e60e23bcd)
[11:26:30] PM io.netty.util.concurrent.AbstractEventExecutor safeExecute
WARNING: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@2c498673
java.lang.Error: Method became inaccessible: PostLoginEvent(player=PBunnny)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:49)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:377)
    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:526)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:326)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalAccessException: Class net.md_5.bungee.event.EventHandlerMethod can not access a member of class com.djrapitops.pluginbridge.plan.viaversion.BungeePlayerVersionListener with modifiers "public"
    at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
    at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
    at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
    at java.lang.reflect.Method.invoke(Method.java:491)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
    ... 7 more

**Comment by Rsl1122** [comment]
This DEV release has this issue fixed - 4.5.1 will be out later next week
https://github.com/Rsl1122/Plan-PlayerAnalytics/releases/tag/4.5.1-DEV1
