### ISSUE TITLE
SIGSEGV on Paper server startup.

### ISSUE THREAD

**Issue by joshuaahklein** [Rsl1122/Plan-PlayerAnalytics#778]
### Describe the bug

Server crashes shortly after startup with SIGSEGV.  This only started occurring after I installed Plan.

### Server information

Plan-4.5.0-bukkit-bungee

System Info: Java 1.8 (OpenJDK 64-Bit Server VM 25.181-b13) 
Host: Linux 4.4.0-124-generic (amd64)
Paper version git-Paper-425 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

Additional plugins:
dynmap v3.0-beta-2-138
LuckPerms v4.3.17
mcMMO v1.6.0-SNAPSHOT
Essentials v2.15.0.55
HeadsPlus v5.1.10
CoreProtect v2.15.1

### Exceptions & Other Logs

[19:46:52 INFO]: [Plan] All database patches already applied.
A fatal error has been detected by the Java Runtime Environment:
SIGSEGV (0xb) at pc=0x000000000000b32e, pid=26, tid=0x00007f43e5455ae8
JRE version: OpenJDK Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
Java VM: OpenJDK 64-Bit Server VM (25.181-b13 mixed mode linux-amd64 compressed oops)
Derivative: IcedTea 3.9.0
Distribution: Custom build (Tue Oct 23 11:27:22 UTC 2018)
Problematic frame:
C 0x000000000000b32e
Core dump written. Default location: /home/container/core or core.26
An error report file with more information is saved as:
/home/container/hs_err_pid26.log
If you would like to submit a bug report, please include
instructions on how to reproduce the bug and visit:
http://icedtea.classpath.org/bugzilla
/entrypoint.sh: line 15: 26 Segmentation fault (core dumped) java -Xms128M -Xmx8192M -jar server.jar

### Additional information

N/A

**Frequency of occurrence**: Shortly after server startup.

**Other:**

**Comment by Rsl1122** [comment]
This seems to be a problem in sqlite, does it occur every time? I suggest trying mysql

**Comment by joshuaahklein** [comment]
Tried changing 'SQLite' in configuration file to 'MySQL' and reloading the plugin, as well as restarting the server.  This is the result:

plan reload=> [20:14:52 INFO]: [Plan] Processing critical unprocessed tasks. (0)
[20:14:52 INFO]: [Plan] Processing complete.
[20:14:52 INFO]: [Plan] Player Analytics Disabled.
[20:14:52 INFO]: [Plan] You're using the latest version.
[20:14:53 ERROR]: [global] Plan-v4.5.0
plan.com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
at plan.com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:576) ~[?:?]
at plan.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562) ~[?:?]
at plan.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[?:?]
at plan.com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[?:?]
at com.djrapitops.plan.system.database.databases.sql.MySQLDB.setupDataSource(MySQLDB.java:94) ~[?:?]
at com.djrapitops.plan.system.database.databases.sql.SQLDB.init(SQLDB.java:140) ~[?:?]
at com.djrapitops.plan.system.database.DBSystem.enable(DBSystem.java:89) ~[?:?]
at com.djrapitops.plan.system.database.BukkitDBSystem.enable(BukkitDBSystem.java:51) ~[?:?]
at com.djrapitops.plan.system.PlanSystem.enableSystems(PlanSystem.java:121) ~[?:?]
at com.djrapitops.plan.system.PlanSystem.enable(PlanSystem.java:101) ~[?:?]
at com.djrapitops.plan.Plan.onEnable(Plan.java:55) ~[?:?]
at com.djrapitops.plugin.PluginCommon.reload(PluginCommon.java:16) ~[?:?]
at com.djrapitops.plugin.BukkitPlugin.reloadPlugin(BukkitPlugin.java:99) ~[?:?]
at com.djrapitops.plan.command.commands.ReloadCommand$1.run(ReloadCommand.java:51) ~[?:?]
at com.djrapitops.plugin.task.bukkit.BukkitRunnableFactory$1.run(BukkitRunnableFactory.java:32) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[server.jar:git-Paper-425]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[server.jar:git-Paper-425]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[server.jar:git-Paper-425]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_181]
at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[server.jar:git-Paper-425]
at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990) ~[server.jar:git-Paper-425]
at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:342) ~[server.jar:git-Paper-425]
at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2197) ~[server.jar:git-Paper-425]
at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2230) ~[server.jar:git-Paper-425]
at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2025) ~[server.jar:git-Paper-425]
at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778) ~[server.jar:git-Paper-425]
at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[server.jar:git-Paper-425]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_181]
at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[server.jar:git-Paper-425]
at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386) ~[server.jar:git-Paper-425]
at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[server.jar:git-Paper-425]
at plan.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136) ~[?:?]
at plan.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369) ~[?:?]
at plan.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198) ~[?:?]
at plan.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467) ~[?:?]
at plan.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541) ~[?:?]
... 19 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_181]
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_181]
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_181]
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_181]
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_181]
at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_181]
at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211) ~[server.jar:git-Paper-425]
at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:301) ~[server.jar:git-Paper-425]
at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2197) ~[server.jar:git-Paper-425]
at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2230) ~[server.jar:git-Paper-425]
at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2025) ~[server.jar:git-Paper-425]
at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778) ~[server.jar:git-Paper-425]
at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[server.jar:git-Paper-425]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_181]
at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[server.jar:git-Paper-425]
at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386) ~[server.jar:git-Paper-425]
at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[server.jar:git-Paper-425]
at plan.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136) ~[?:?]
at plan.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369) ~[?:?]
at plan.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198) ~[?:?]
at plan.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467) ~[?:?]
at plan.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541) ~[?:?]
... 19 more
[20:14:53 ERROR]: [Plan] Plugin Failed to Initialize Correctly. If this issue is caused by config settings you can use /plan reload
[20:14:53 ERROR]: [Plan] This error should be reported at https://github.com/Rsl1122/Plan-PlayerAnalytics/issues
[20:14:53 INFO]: [Plan] Processing critical unprocessed tasks. (0)
[20:14:53 INFO]: [Plan] Processing complete.
[20:14:53 INFO]: [Plan] Player Analytics Disabled.
[20:14:53 INFO]: Reload Complete

**Comment by Rsl1122** [comment]
The second error states that Plan could not connect to the MySQL database.

Make sure that the mysql user in use has access permissions to the database in that address.

**Comment by joshuaahklein** [comment]
Ahh, that appeared to be an issue on my end.  Now that I've fixed that, the plugin seems to be working.  I'll update you if I come across anything else -- thanks for your help!

**Comment by Rsl1122** [comment]
Closing this issue as I don't know how to address it. 
It might already have been fixed with the changes that fixed tests crashing the JVM.
