### ISSUE TITLE
Java 11 missing javax xml dependency

### ISSUE THREAD

**Issue by Miclebrick** [Rsl1122/Plan-PlayerAnalytics#829]
```
[00:21:23 ERROR]: Exception in thread "Plan WebServer Thread-7" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
[00:21:23 ERROR]:       at com.djrapitops.plan.utilities.PassEncryptUtil.fromBase64(PassEncryptUtil.java:180)
[00:21:23 ERROR]:       at com.djrapitops.plan.utilities.PassEncryptUtil.verifyPassword(PassEncryptUtil.java:116)
[00:21:23 ERROR]:       at com.djrapitops.plan.utilities.PassEncryptUtil.verifyPassword(PassEncryptUtil.java:81)
[00:21:23 ERROR]:       at com.djrapitops.plan.system.webserver.auth.BasicAuthentication.getWebUser(BasicAuthentication.java:64)
[00:21:23 ERROR]:       at com.djrapitops.plan.system.webserver.pages.PlayerPageHandler.isAuthorized(PlayerPageHandler.java:106)
[00:21:23 ERROR]:       at com.djrapitops.plan.system.webserver.ResponseHandler.getResponse(ResponseHandler.java:157)
[00:21:23 ERROR]:       at com.djrapitops.plan.system.webserver.ResponseHandler.getResponse(ResponseHandler.java:104)
[00:21:23 ERROR]:       at com.djrapitops.plan.system.webserver.RequestHandler.handle(RequestHandler.java:94)
[00:21:23 ERROR]:       at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
[00:21:23 ERROR]:       at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
[00:21:23 ERROR]:       at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
[00:21:23 ERROR]:       at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:692)
[00:21:23 ERROR]:       at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
[00:21:23 ERROR]:       at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:664)
[00:21:23 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[00:21:23 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[00:21:23 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:834)
```
Probably removed in java 11 or something

**Comment by Rsl1122** [comment]
Yes would seem like so
https://jaxenter.com/jdk-11-java-ee-modules-140674.html

**Comment by Miclebrick** [comment]
Would it be possible to include the library/use a different one in order to provide compatibility for servers running 11?

**Comment by Miclebrick** [comment]
It looks like it just uses it for base64, I'll make a PR that uses Base64 instead

**Comment by Miclebrick** [comment]
can confirm it works on java 11 with this fix

**Comment by Rsl1122** [comment]
Alright thanks.
