### ISSUE TITLE
ConcurrentModificationException during/following Boot Analysis. 

### ISSUE THREAD

**Issue by zedwick** [Rsl1122/Plan-PlayerAnalytics#84]
**Plan Version:** 3.0.1
**Server Version:** git-Paper-1094 (1.11.2)
**Database Type:** sqlite
**Command Causing Issue:** None, just during server boot

**Description:**
Shortly after server boot, following "Starting Boot Analysis..".

I did not notice this in 3.0.0, so I assume it was introduced in 3.0.1.

**Steps to Reproduce:**

1. Start server

**Stack Trace - Console/Errors.txt contents:**
```
[17:18:51 INFO]: [Plan] Analysis | Starting Boot Analysis..
[17:18:56 WARN]: [Plan] Plugin Plan v3.0.1 generated an exception while executing task 321
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_45]
        at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_45]
        at main.java.com.djrapitops.plan.ui.graphs.PlayerActivityGraphCreator.generateDataArray(PlayerActivityGraphCreator.java:32) ~[?:?]
        at main.java.com.djrapitops.plan.utilities.Analysis.createPlayerActivityGraphs(Analysis.java:326) ~[?:?]
        at main.java.com.djrapitops.plan.utilities.Analysis.analyzeData(Analysis.java:241) ~[?:?]
        at main.java.com.djrapitops.plan.utilities.Analysis.analyze(Analysis.java:135) ~[?:?]
        at main.java.com.djrapitops.plan.utilities.Analysis$1.run(Analysis.java:67) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1094]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.11.2.jar:git-Paper-1094]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.11.2.jar:git-Paper-1094]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

**Comment by Rsl1122** [comment]
Ah yes. Will be fixed shortly.
