### ISSUE TITLE
Database update errors 4.5.2->4.6.0-DEV1

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#843]
### Server information
Spigot 1.13.2 latest (today)
Plan 4.6.0-DEV1 aka 4.5.2-b1

### Describe the bug
Plan fails to load on server start.
```
[18:19:08] [Craft Scheduler Thread - 4/INFO]: [Plan] Applying Patch: WorldsOptimizationPatch..
[18:19:08] [Craft Scheduler Thread - 4/ERROR]: [Plan] ----------------------------------------------------
[18:19:08] [Craft Scheduler Thread - 4/ERROR]: [Plan] Database Patching failed, plugin has to be disabled. Please report this issue
[18:19:08] [Craft Scheduler Thread - 4/ERROR]: [Plan] ----------------------------------------------------
[18:19:08] [Craft Scheduler Thread - 4/ERROR]: [Plan] Error was caught by com.djrapitops.plan.system.database.databases.sql.PatchTask
com.djrapitops.plan.api.exceptions.database.DBOpException: WorldsOptimizationPatch failed.
        at com.djrapitops.plan.system.database.databases.sql.patches.WorldsOptimizationPatch.apply(WorldsOptimizationPatch.java:62) ~[Plan-4.5.2-b1.jar:?]
        at com.djrapitops.plan.system.database.databases.sql.PatchTask.applyPatches(PatchTask.java:68) ~[Plan-4.5.2-b1.jar:?]
        at com.djrapitops.plan.system.database.databases.sql.PatchTask.run(PatchTask.java:50) [Plan-4.5.2-b1.jar:?]
        at com.djrapitops.plugin.task.bukkit.BukkitRunnableFactory$1.run(BukkitRunnableFactory.java:32) [Plan-4.5.2-b1.jar:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) [spigot-1.13.2.jar-2018-12-13-1024:git-Spigot-140f654-b446cb5]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.2.jar-2018-12-13-1024:git-Spigot-140f654-b446cb5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: com.djrapitops.plan.api.exceptions.database.DBOpException: SQL Failed: ALTER TABLE plan_worlds RENAME TO temp_worlds; Query returns results
        at com.djrapitops.plan.api.exceptions.database.DBOpException.forCause(DBOpException.java:37) ~[?:?]
        at com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:318) ~[?:?]
        at com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:325) ~[?:?]
        at com.djrapitops.plan.system.database.databases.sql.patches.Patch.renameTable(Patch.java:134) ~[?:?]
        at com.djrapitops.plan.system.database.databases.sql.patches.WorldsOptimizationPatch.tempOldTable(WorldsOptimizationPatch.java:68) ~[?:?]
        at com.djrapitops.plan.system.database.databases.sql.patches.WorldsOptimizationPatch.apply(WorldsOptimizationPatch.java:46) ~[?:?]
        ... 8 more
Caused by: java.sql.SQLException: Query returns results
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:95) ~[spigot-1.13.2.jar-2018-12-13-1024:git-Spigot-140f654-b446cb5]
        at com.djrapitops.plan.system.database.databases.sql.processing.ExecStatement.execute(ExecStatement.java:37) ~[?:?]
        at com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:315) ~[?:?]
        at com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:325) ~[?:?]
        at com.djrapitops.plan.system.database.databases.sql.patches.Patch.renameTable(Patch.java:134) ~[?:?]
        at com.djrapitops.plan.system.database.databases.sql.patches.WorldsOptimizationPatch.tempOldTable(WorldsOptimizationPatch.java:68) ~[?:?]
        at com.djrapitops.plan.system.database.databases.sql.patches.WorldsOptimizationPatch.apply(WorldsOptimizationPatch.java:46) ~[?:?]
        ... 8 more
[18:19:08] [Craft Scheduler Thread - 4/ERROR]: [Plan] CRITICAL error triggered a plugin shutdown.
[18:19:08] [Craft Scheduler Thread - 4/INFO]: [Plan] Processing critical unprocessed tasks. (0)
[18:19:08] [Craft Scheduler Thread - 4/INFO]: [Plan] Processing complete.
[18:19:08] [Craft Scheduler Thread - 4/INFO]: [Plan] Webserver has been disabled.
[18:19:08] [Craft Scheduler Thread - 4/INFO]: [Plan] Player Analytics Disabled.
```

**Comment by SlimeDog** [comment]
Debug:true version of the above:
```
[18:28:49] [Craft Scheduler Thread - 0/INFO]: [Plan] [DEBUG] [] Applying Patch: WorldsOptimizationPatch..
[18:28:49] [Craft Scheduler Thread - 0/INFO]: [Plan] Applying Patch: WorldsOptimizationPatch..
[18:28:49] [Craft Scheduler Thread - 0/INFO]: [Plan] [DEBUG] [] ----------------------------------------------------
[18:28:49] [Craft Scheduler Thread - 0/ERROR]: [Plan] ----------------------------------------------------
[18:28:49] [Craft Scheduler Thread - 0/INFO]: [Plan] [DEBUG] [] Database Patching failed, plugin has to be disabled. Please report this issue
[18:28:49] [Craft Scheduler Thread - 0/ERROR]: [Plan] Database Patching failed, plugin has to be disabled. Please report this issue
[18:28:49] [Craft Scheduler Thread - 0/INFO]: [Plan] [DEBUG] [] ----------------------------------------------------
[18:28:49] [Craft Scheduler Thread - 0/ERROR]: [Plan] ----------------------------------------------------
[18:28:49] [Craft Scheduler Thread - 0/ERROR]: [Plan] Error was caught by com.djrapitops.plan.system.database.databases.sql.PatchTask
com.djrapitops.plan.api.exceptions.database.DBOpException: WorldsOptimizationPatch failed.
        at com.djrapitops.plan.system.database.databases.sql.patches.WorldsOptimizationPatch.apply(WorldsOptimizationPatch.java:62) ~[Plan-4.5.2-b1.jar:?]
        at com.djrapitops.plan.system.database.databases.sql.PatchTask.applyPatches(PatchTask.java:68) ~[Plan-4.5.2-b1.jar:?]
        at com.djrapitops.plan.system.database.databases.sql.PatchTask.run(PatchTask.java:50) [Plan-4.5.2-b1.jar:?]
        at com.djrapitops.plugin.task.bukkit.BukkitRunnableFactory$1.run(BukkitRunnableFactory.java:32) [Plan-4.5.2-b1.jar:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) [spigot-1.13.2.jar-2018-12-13-1024:git-Spigot-140f654-b446cb5]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.2.jar-2018-12-13-1024:git-Spigot-140f654-b446cb5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: com.djrapitops.plan.api.exceptions.database.DBOpException: SQL Failed: ALTER TABLE plan_worlds RENAME TO temp_worlds; Query returns results
        at com.djrapitops.plan.api.exceptions.database.DBOpException.forCause(DBOpException.java:37) ~[?:?]
        at com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:318) ~[?:?]
        at com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:325) ~[?:?]
        at com.djrapitops.plan.system.database.databases.sql.patches.Patch.renameTable(Patch.java:134) ~[?:?]
        at com.djrapitops.plan.system.database.databases.sql.patches.WorldsOptimizationPatch.tempOldTable(WorldsOptimizationPatch.java:68) ~[?:?]
        at com.djrapitops.plan.system.database.databases.sql.patches.WorldsOptimizationPatch.apply(WorldsOptimizationPatch.java:46) ~[?:?]
        ... 8 more
Caused by: java.sql.SQLException: Query returns results
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:95) ~[spigot-1.13.2.jar-2018-12-13-1024:git-Spigot-140f654-b446cb5]
        at com.djrapitops.plan.system.database.databases.sql.processing.ExecStatement.execute(ExecStatement.java:37) ~[?:?]
        at com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:315) ~[?:?]
        at com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:325) ~[?:?]
        at com.djrapitops.plan.system.database.databases.sql.patches.Patch.renameTable(Patch.java:134) ~[?:?]
        at com.djrapitops.plan.system.database.databases.sql.patches.WorldsOptimizationPatch.tempOldTable(WorldsOptimizationPatch.java:68) ~[?:?]
        at com.djrapitops.plan.system.database.databases.sql.patches.WorldsOptimizationPatch.apply(WorldsOptimizationPatch.java:46) ~[?:?]
        ... 8 more
[18:28:49] [Craft Scheduler Thread - 0/INFO]: [Plan] [DEBUG] [] CRITICAL error triggered a plugin shutdown.
[18:28:49] [Craft Scheduler Thread - 0/ERROR]: [Plan] CRITICAL error triggered a plugin shutdown.
[18:28:49] [Craft Scheduler Thread - 0/INFO]: [Plan] [DEBUG] [] Processing critical unprocessed tasks. (0)
[18:28:49] [Craft Scheduler Thread - 0/INFO]: [Plan] Processing critical unprocessed tasks. (0)
[18:28:49] [Craft Scheduler Thread - 0/INFO]: [Plan] [DEBUG] [] Processing complete.
[18:28:49] [Craft Scheduler Thread - 0/INFO]: [Plan] Processing complete.
[18:28:49] [Craft Scheduler Thread - 0/INFO]: [Plan] [DEBUG] [] SQLite database.db: Closed Connection
[18:28:49] [Craft Scheduler Thread - 0/INFO]: [Plan] [DEBUG] [] Webserver has been disabled.
[18:28:49] [Craft Scheduler Thread - 0/INFO]: [Plan] Webserver has been disabled.
[18:28:49] [Craft Scheduler Thread - 0/INFO]: [Plan] [DEBUG] [] Player Analytics Disabled.
[18:28:49] [Craft Scheduler Thread - 0/INFO]: [Plan] Player Analytics Disabled.
```

**Comment by Rsl1122** [comment]
Thanks for reporting, these are the kind of issues I was hoping to catch.

Which database is in use?

**Comment by Rsl1122** [comment]
Alright I have dug deeper into the issue, and the exception could not be found from Google easily, so I'm assuming this is a first.

1.12 was not causing the issue so I looked at the differences, and Spigot has updated SQLite from 3.18.0 to 3.25.2

On [the SQLite documentation page](https://www.sqlite.org/lang_altertable.html) for `ALTER TABLE` they say

> **Compatibility Note**: The behavior of ALTER TABLE when renaming a table was enhanced in versions 3.25.0 (2018-09-15) and 3.26.0 (2018-12-01) in order to carry the rename operation forward into triggers and views that reference the renamed table. This is considered an improvement. Applications that depend on the older (and arguably buggy) behavior can use the PRAGMA legacy_alter_table=ON statement to make ALTER TABLE RENAME behavior as it did prior to version 3.25.0. 

I'm guessing some "triggers" fire and the statement now returns something, so I'll probably have to set `PRAGMA legacy_alter_table=ON`

I'll let you know when a fix is available.

**Comment by SlimeDog** [comment]
> I'll let you know when a fix is available.

Thank you.

**Comment by Rsl1122** [comment]
Fixed in DEV2
https://github.com/Rsl1122/Plan-PlayerAnalytics/releases/tag/4.6.0-DEV2

**Comment by SlimeDog** [comment]
Confirmed fixed in DEV2
