### ISSUE TITLE
SQL exceptions / patch failed "CRITICAL" error.

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#860]
Paper dev 488 (Spigot 1.13.2)
Updated from Plan v4.5.1 to 4.6.0 DEV2.

Error log.
https://paste.ubuntu.com/p/wDT6Nm6VRZ/

```
[04:41:29] [Craft Scheduler Thread - 20/INFO]: [Plan] Applying Patch: WorldsOptimizationPatch..
[04:41:29] [Craft Scheduler Thread - 20/INFO]: [Plan] Applying Patch: WorldTimesOptimizationPatch..
[04:41:29] [Craft Scheduler Thread - 20/INFO]: [Plan] Applying Patch: KillsOptimizationPatch..
[04:41:29] [Craft Scheduler Thread - 20/INFO]: [Plan] Applying Patch: SessionsOptimizationPatch..
[04:41:30] [Craft Scheduler Thread - 20/INFO]: [Plan] Applying Patch: PingOptimizationPatch..
[04:41:31] [Craft Scheduler Thread - 20/INFO]: [Plan] Applying Patch: NicknamesOptimizationPatch..
[04:41:31] [Craft Scheduler Thread - 20/INFO]: [Plan] Applying Patch: UserInfoOptimizationPatch..
[04:41:31] [Craft Scheduler Thread - 20/INFO]: [Plan] Applying Patch: GeoInfoOptimizationPatch..
[04:41:31] [Craft Scheduler Thread - 20/INFO]: [Plan] All database patches applied successfully.
[04:41:44] [Craft Scheduler Thread - 1/ERROR]: [Plan] Error was caught by com.djrapitops.plan.system.database.databases.sql.SQLDB$1
com.djrapitops.plan.api.exceptions.database.DBOpException: SQL Failed: DELETE FROM plan_users WHERE (uuid=?); Cannot delete or update a parent row: a foreign key constraint fails (`playeranalytics`.`temp_sessions`, CONSTRAINT `temp_sessions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `plan_users` (`id`))
	at com.djrapitops.plan.api.exceptions.database.DBOpException.forCause(DBOpException.java:37) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:318) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.tables.Table.execute(Table.java:152) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.tables.UserUUIDTable.removeUser(UserUUIDTable.java:41) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.operation.SQLRemoveOps.player(SQLRemoveOps.java:46) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.SQLDB.clean(SQLDB.java:288) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.SQLDB.access$000(SQLDB.java:61) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.SQLDB$1.run(SQLDB.java:168) ~[?:?]
	at com.djrapitops.plugin.task.bukkit.BukkitRunnableFactory$1.run(BukkitRunnableFactory.java:32) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-488]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-488]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`playeranalytics`.`temp_sessions`, CONSTRAINT `temp_sessions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `plan_users` (`id`))
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[patched_1.13.2.jar:git-Paper-488]
	at plan.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[?:?]
	at plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.processing.ExecStatement.callExecute(ExecStatement.java:46) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.processing.ExecStatement.execute(ExecStatement.java:37) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:315) ~[?:?]
	... 13 more
```

```
[04:51:26] [Craft Scheduler Thread - 6/INFO]: [Plan] Applying Patch: WorldsOptimizationPatch..
[04:51:26] [Craft Scheduler Thread - 6/ERROR]: [Plan] ----------------------------------------------------
[04:51:26] [Craft Scheduler Thread - 6/ERROR]: [Plan] Database Patching failed, plugin has to be disabled. Please report this issue
[04:51:26] [Craft Scheduler Thread - 6/ERROR]: [Plan] ----------------------------------------------------
[04:51:26] [Craft Scheduler Thread - 6/ERROR]: [Plan] Error was caught by com.djrapitops.plan.system.database.databases.sql.PatchTask
com.djrapitops.plan.api.exceptions.database.DBOpException: WorldsOptimizationPatch failed.
	at com.djrapitops.plan.system.database.databases.sql.patches.WorldsOptimizationPatch.apply(WorldsOptimizationPatch.java:62) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.PatchTask.applyPatches(PatchTask.java:68) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.PatchTask.run(PatchTask.java:50) ~[?:?]
	at com.djrapitops.plugin.task.bukkit.BukkitRunnableFactory$1.run(BukkitRunnableFactory.java:32) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-488]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-488]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.djrapitops.plan.api.exceptions.database.DBOpException: SQL Failed: INSERT INTO plan_worlds (id, server_uuid, world_name) SELECT id, (SELECT plan_servers.uuid FROM plan_servers WHERE plan_servers.id = temp_worlds.server_id LIMIT 1), world_name FROM temp_worlds; Duplicate entry '1' for key 'PRIMARY'
	at com.djrapitops.plan.api.exceptions.database.DBOpException.forCause(DBOpException.java:37) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:318) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:325) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.patches.WorldsOptimizationPatch.apply(WorldsOptimizationPatch.java:49) ~[?:?]
	... 9 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1' for key 'PRIMARY'
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[patched_1.13.2.jar:git-Paper-488]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[patched_1.13.2.jar:git-Paper-488]
	at plan.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[?:?]
	at plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.processing.ExecStatement.callExecute(ExecStatement.java:46) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.processing.ExecStatement.execute(ExecStatement.java:37) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:315) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:325) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.patches.WorldsOptimizationPatch.apply(WorldsOptimizationPatch.java:49) ~[?:?]
	... 9 more
[04:51:26] [Craft Scheduler Thread - 6/ERROR]: [Plan] CRITICAL error triggered a plugin shutdown.
[04:51:26] [Craft Scheduler Thread - 6/INFO]: [Plan] Processing critical unprocessed tasks. (0)
[04:51:26] [Craft Scheduler Thread - 6/INFO]: [Plan] Processing complete.
[04:51:26] [Craft Scheduler Thread - 6/INFO]: [Plan] Webserver has been disabled.
[04:51:26] [Craft Scheduler Thread - 6/INFO]: [Plan] Player Analytics Disabled.
[04:51:51] [Server thread/INFO]: [Plan] Disabling Plan v4.5.2-b2
[04:51:51] [Server thread/INFO]: [Plan] Processing critical unprocessed tasks. (0)
[04:51:51] [Server thread/INFO]: [Plan] Processing complete.
[04:51:51] [Server thread/INFO]: [Plan] Webserver has been disabled.
[04:51:51] [Server thread/INFO]: [Plan] Player Analytics Disabled.
```

**Comment by mibby** [comment]
I manually purged the world and temp tables and it seems to be fine now. But if it is an actual upgrade issue, may want to look into it. :)

**Comment by Rsl1122** [comment]
Since "Patches failing" seemed like a very common bug in dev releases I decided to write regression tests for them for every database type.

This should keep this type of regression bug at bay in the future.
Managed to find a couple other bugs too. 

I just wanted to share because it won't be "visible work" to most of the users :)

**Comment by Rsl1122** [comment]
Something funky going on, might be due to having started with another dev version

```
17:20:50 [INFO] [Plan] Applying Patch: WorldTimesOptimizationPatch..
17:20:50 [SEVERE] [Plan] ----------------------------------------------------
17:20:50 [SEVERE] [Plan] Database Patching failed, plugin has to be disabled. Please report this issue
17:20:50 [SEVERE] [Plan] ----------------------------------------------------
17:20:50 [SEVERE] [Plan] Error was caught by com.djrapitops.plan.system.database.databases.sql.PatchTask
com.djrapitops.plan.api.exceptions.database.DBOpException: WorldTimesOptimizationPatch failed.
    at com.djrapitops.plan.system.database.databases.sql.patches.WorldTimesOptimizationPatch.apply(WorldTimesOptimizationPatch.java:74)
    at com.djrapitops.plan.system.database.databases.sql.PatchTask.applyPatches(PatchTask.java:68)
    at com.djrapitops.plan.system.database.databases.sql.PatchTask.run(PatchTask.java:50)
    at com.djrapitops.plugin.task.bungee.BungeeRunnableFactory$1.run(BungeeRunnableFactory.java:32)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: com.djrapitops.plan.api.exceptions.database.DBInitException: Failed to create table: plan_world_times
    at com.djrapitops.plan.system.database.databases.sql.tables.Table.createTable(Table.java:60)
    at com.djrapitops.plan.system.database.databases.sql.tables.WorldTimesTable.createTable(WorldTimesTable.java:81)
    at com.djrapitops.plan.system.database.databases.sql.patches.WorldTimesOptimizationPatch.apply(WorldTimesOptimizationPatch.java:49)
    ... 7 more
Caused by: com.djrapitops.plan.api.exceptions.database.DBOpException: SQL Failed: CREATE TABLE IF NOT EXISTS plan_world_times (id integer NOT NULL AUTO_INCREMENT, uuid varchar(36) NOT NULL, world_id integer NOT NULL, server_uuid varchar(36) NOT NULL, session_id integer NOT NULL, survival_time bigint NOT NULL DEFAULT 0, creative_time bigint NOT NULL DEFAULT 0, adventure_time bigint NOT NULL DEFAULT 0, spectator_time bigint NOT NULL DEFAULT 0, PRIMARY KEY (id), FOREIGN KEY(world_id) REFERENCES plan_worlds(id), FOREIGN KEY(session_id) REFERENCES plan_sessions(id)); Can't create table `plan`.`plan_world_times` (errno: 150 "Foreign key constraint is incorrectly formed")
    at com.djrapitops.plan.api.exceptions.database.DBOpException.forCause(DBOpException.java:37)
    at com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:322)
    at com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:329)
    at com.djrapitops.plan.system.database.databases.sql.tables.Table.createTable(Table.java:58)
    ... 9 more
Caused by: java.sql.SQLException: Can't create table `plan`.`plan_world_times` (errno: 150 "Foreign key constraint is incorrectly formed")
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
    at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1242)
    at plan.com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
    at plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
    at com.djrapitops.plan.system.database.databases.sql.processing.ExecStatement.callExecute(ExecStatement.java:48)
    at com.djrapitops.plan.system.database.databases.sql.processing.ExecStatement.execute(ExecStatement.java:37)
    at com.djrapitops.plan.system.database.databases.sql.SQLDB.execute(SQLDB.java:319)
    ... 11 more
17:20:50 [SEVERE] [Plan] CRITICAL error triggered a plugin shutdown.
```
