### ISSUE TITLE
Plan fails to start on BungeeCord [4.6.0 DEV3]

### ISSUE THREAD

**Issue by Rsl1122** [Rsl1122/Plan-PlayerAnalytics#874]
### Describe the bug

Plan 4.6.0 DEV3 fails to start on BungeeCord

### Exceptions & Other Logs

```
17:10:21 [SEVERE] [Plan] Error was caught by com.djrapitops.plan.PlanBungee
java.lang.IllegalArgumentException: Can not add a node with empty path
    at com.djrapitops.plan.system.settings.config.ConfigNode.addNode(ConfigNode.java:106)
    at com.djrapitops.plan.system.settings.config.ConfigNode.copyMissing(ConfigNode.java:306)
    at com.djrapitops.plan.system.settings.config.ConfigNode.copyMissing(ConfigNode.java:307)
    at com.djrapitops.plan.system.settings.config.ConfigNode.copyMissing(ConfigNode.java:307)
    at com.djrapitops.plan.system.settings.config.Config.read(Config.java:81)
    at com.djrapitops.plan.system.settings.config.Config.<init>(Config.java:57)
    at com.djrapitops.plan.system.settings.config.PlanConfig.<init>(PlanConfig.java:48)
    at com.djrapitops.plan.system.settings.config.PlanConfig_Factory.provideInstance(PlanConfig_Factory.java:30)
    at com.djrapitops.plan.system.settings.config.PlanConfig_Factory.get(PlanConfig_Factory.java:25)
    at com.djrapitops.plan.system.settings.config.PlanConfig_Factory.get(PlanConfig_Factory.java:8)
    at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
    at dagger.internal.DelegateFactory.get(DelegateFactory.java:36)
    at com.djrapitops.plan.system.settings.ProxyConfigSystem_Factory.provideInstance(ProxyConfigSystem_Factory.java:72)
    at com.djrapitops.plan.system.settings.ProxyConfigSystem_Factory.get(ProxyConfigSystem_Factory.java:52)
    at com.djrapitops.plan.system.settings.ProxyConfigSystem_Factory.get(ProxyConfigSystem_Factory.java:14)
    at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
    at com.djrapitops.plan.system.PlanSystem_Factory.provideInstance(PlanSystem_Factory.java:148)
    at com.djrapitops.plan.system.PlanSystem_Factory.get(PlanSystem_Factory.java:106)
    at com.djrapitops.plan.system.PlanSystem_Factory.get(PlanSystem_Factory.java:24)
    at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
    at com.djrapitops.plan.DaggerPlanBungeeComponent.system(DaggerPlanBungeeComponent.java:1102)
    at com.djrapitops.plan.PlanBungee.onEnable(PlanBungee.java:45)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:226)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
17:10:21 [SEVERE] [Plan] CRITICAL error triggered a plugin shutdown.
```

Another exception on the shutdown that follows the critical error

```
java.lang.NullPointerException
    at com.djrapitops.plan.PlanBungee.onDisable(PlanBungee.java:80)
    at com.djrapitops.plugin.logging.error.CriticalErrorHandler.log(CriticalErrorHandler.java:28)
    at com.djrapitops.plugin.logging.error.CombineErrorHandler.log(CombineErrorHandler.java:28)
    at com.djrapitops.plan.PlanBungee.onEnable(PlanBungee.java:65)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:226)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

**Comment by Rsl1122** [comment]
Caused by empty key `:` on one line in the config
![image](https://user-images.githubusercontent.com/24460436/50839715-8ecffd00-1369-11e9-8200-deb7e3a5bf4f.png)
