### ISSUE TITLE
Error was caught by com.djrapitops.plan.system.processing.Processing

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#880]
Plan 4.6.0 DEV4

```
[02:30:25] [Plan Critical-pool-1/ERROR]: [Plan] Error was caught by com.djrapitops.plan.system.processing.Processing
com.djrapitops.plan.api.exceptions.database.DBOpException: SQL Failed: INSERT INTO plan_kills (killer_uuid, victim_uuid, server_uuid, session_id, date, weapon) VALUES (?, ?, ?, ?, ?, ?); Cannot add or update a child row: a foreign key constraint fails (`playeranalytics`.`plan_kills`, CONSTRAINT `plan_kills_ibfk_1` FOREIGN KEY (`session_id`) REFERENCES `temp_sessions` (`id`))
	at com.djrapitops.plan.api.exceptions.database.DBOpException.forCause(DBOpException.java:37) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.SQLDB.executeBatch(SQLDB.java:378) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.tables.Table.executeBatch(Table.java:156) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.tables.KillsTable.savePlayerKills(KillsTable.java:185) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.tables.SessionsTable.saveSession(SessionsTable.java:131) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.operation.SQLSaveOps.session(SQLSaveOps.java:134) ~[?:?]
	at com.djrapitops.plan.system.cache.SessionCache.endSession(SessionCache.java:92) ~[?:?]
	at com.djrapitops.plan.system.processing.processors.player.EndSessionProcessor.run(EndSessionProcessor.java:44) ~[?:?]
	at com.djrapitops.plan.system.processing.Processing.lambda$submitCritical$1(Processing.java:78) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.sql.BatchUpdateException: Cannot add or update a child row: a foreign key constraint fails (`playeranalytics`.`plan_kills`, CONSTRAINT `plan_kills_ibfk_1` FOREIGN KEY (`session_id`) REFERENCES `temp_sessions` (`id`))
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.13.2.jar:git-Paper-500]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[patched_1.13.2.jar:git-Paper-500]
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163) ~[patched_1.13.2.jar:git-Paper-500]
	at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1632) ~[patched_1.13.2.jar:git-Paper-500]
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1298) ~[patched_1.13.2.jar:git-Paper-500]
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970) ~[patched_1.13.2.jar:git-Paper-500]
	at plan.com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[?:?]
	at plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.processing.ExecStatement.executeBatch(ExecStatement.java:57) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.SQLDB.executeBatch(SQLDB.java:375) ~[?:?]
	... 11 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`playeranalytics`.`plan_kills`, CONSTRAINT `plan_kills_ibfk_1` FOREIGN KEY (`session_id`) REFERENCES `temp_sessions` (`id`))
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.13.2.jar:git-Paper-500]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[patched_1.13.2.jar:git-Paper-500]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936) ~[patched_1.13.2.jar:git-Paper-500]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[patched_1.13.2.jar:git-Paper-500]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[patched_1.13.2.jar:git-Paper-500]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[patched_1.13.2.jar:git-Paper-500]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[patched_1.13.2.jar:git-Paper-500]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[patched_1.13.2.jar:git-Paper-500]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[patched_1.13.2.jar:git-Paper-500]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[patched_1.13.2.jar:git-Paper-500]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[patched_1.13.2.jar:git-Paper-500]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[patched_1.13.2.jar:git-Paper-500]
	at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1593) ~[patched_1.13.2.jar:git-Paper-500]
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1298) ~[patched_1.13.2.jar:git-Paper-500]
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970) ~[patched_1.13.2.jar:git-Paper-500]
	at plan.com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[?:?]
	at plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.processing.ExecStatement.executeBatch(ExecStatement.java:57) ~[?:?]
	at com.djrapitops.plan.system.database.databases.sql.SQLDB.executeBatch(SQLDB.java:375) ~[?:?]
	... 11 more
```

**Comment by Rsl1122** [comment]
It looks like the patches have not completely applied, can you see Applying Patch: KillsOptimizationPatch in the logs?

**Comment by mibby** [comment]
The only patch I can see in the logs from 01/12 is;

```
[06:16:15] [Craft Scheduler Thread - 12/INFO]: [Plan] Applying Patch: TransferTableRemovalPatch..
[06:16:15] [Craft Scheduler Thread - 12/INFO]: [Plan] All database patches applied successfully.
```

Unless the patch is from an earlier dev build?

**Comment by Rsl1122** [comment]
The error occurs because plan_kills has a bad foreign key reference to temp_sessions and the session where the kill occurred isn't stored in temp_sessions (I'm insure if your database contains temp_sessions, probably not) 

The reference should have been updated by KillsOptimizationPatch when it re-created the plan_kills table

It might be due to the patches applying improperly in an earlier dev version.

There isn't an easy way to re-run the patch that would fix this since it requires reversing the patch, so it needs either 4.5.2 database to run again or dropping the broken table (plan_kills) to fix.

**Comment by mibby** [comment]
@Rsl1122 I dropped the table and let it re-create at start-up, but it didn't seem to recreate anything inside or update when I killed a mob & player. Is it possibly broken?

![link](https://i.imgur.com/LgrX59x.png)

**Comment by Rsl1122** [comment]
The kills are saved along with the session when you leave the server, were you still online when you made that query?

**Comment by mibby** [comment]
I was, yes. Forcing a restart did seem to input what was cached. Testing again by killing a player with the new table, there is no more error. So I presume this is effectively "fixed" and can be closed now. :)

**Comment by Rsl1122** [comment]
Alright, thanks for reporting though :)
