### ISSUE TITLE
Dagger Version conflict with AACH 5.11

### ISSUE THREAD

**Issue by Rsl1122** [Rsl1122/Plan-PlayerAnalytics#885]
### Describe the bug

AdvancedAchievements 5.11 + Plan 4.6.0 cause Plan to fail to load due to dagger version mismatch.

### Server information
Spigot 1.13.2

### Exceptions & Other Logs
```
17.01 15:05:58 [Server] ERROR Error occurred while enabling Plan v4.6.0 (Is it up to date?)
17.01 15:05:58 [Server] INFO java.lang.NoSuchMethodError: dagger.internal.Preconditions.checkBuilderRequirement(Ljava/lang/Object;Ljava/lang/Class;)V
17.01 15:05:58 [Server] INFO at com.djrapitops.plan.DaggerPlanBukkitComponent$Builder.build(DaggerPlanBukkitComponent.java:1541) ~[Plan-4.6.0.jar:?]
17.01 15:05:58 [Server] INFO at com.djrapitops.plan.Plan.onEnable(Plan.java:46) ~[Plan-4.6.0.jar:?]
17.01 15:05:58 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot1132.jar:git-Spigot-f56e2e7-0c715b3]
17.01 15:05:58 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot1132.jar:git-Spigot-f56e2e7-0c715b3]
17.01 15:05:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot1132.jar:git-Spigot-f56e2e7-0c715b3]
17.01 15:05:58 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot1132.jar:git-Spigot-f56e2e7-0c715b3]
17.01 15:05:58 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot1132.jar:git-Spigot-f56e2e7-0c715b3]
17.01 15:05:58 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot1132.jar:git-Spigot-f56e2e7-0c715b3]
17.01 15:05:58 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot1132.jar:git-Spigot-f56e2e7-0c715b3]
17.01 15:05:58 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot1132.jar:git-Spigot-f56e2e7-0c715b3]
17.01 15:05:58 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot1132.jar:git-Spigot-f56e2e7-0c715b3]
17.01 15:05:58 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot1132.jar:git-Spigot-f56e2e7-0c715b3]
17.01 15:05:58 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
```

## Solution

Relocate dagger classes

**Comment by Rsl1122** [comment]
Version with the fix: [Plan#885.zip](https://github.com/Rsl1122/Plan-PlayerAnalytics/files/2769431/Plan.885.zip)
