### ISSUE TITLE
Plugin Plan v2.5.1 generated an exception while executing task 29

### ISSUE THREAD

**Issue by PsychoLynx** [Rsl1122/Plan-PlayerAnalytics#9]
Not really sure as to what caused this error, but I found it in my logs.

[10:51:03] [Craft Scheduler Thread - 57/WARN]: [Plan] Plugin Plan v2.5.1 generated an exception while executing task 29
java.lang.NullPointerException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.ForkJoinTask.reportException(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[?:1.8.0_121]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:1.8.0_121]
	at com.djrapitops.plan.data.cache.DataCacheHandler.saveHandlerDataToCache(DataCacheHandler.java:226) ~[?:?]
	at com.djrapitops.plan.data.cache.DataCacheHandler.access$000(DataCacheHandler.java:27) ~[?:?]
	at com.djrapitops.plan.data.cache.DataCacheHandler$1.run(DataCacheHandler.java:95) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1055]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.11.2.jar:git-Paper-1055]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.11.2.jar:git-Paper-1055]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_121]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at com.djrapitops.plan.data.handlers.GamemodeTimesHandler.saveToCache(GamemodeTimesHandler.java:79) ~[?:?]
	at com.djrapitops.plan.data.cache.DataCacheHandler.saveHandlerDataToCache(DataCacheHandler.java:249) ~[?:?]
	at com.djrapitops.plan.data.cache.DataCacheHandler.lambda$saveHandlerDataToCache$0(DataCacheHandler.java:227) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_121]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_121]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_121]

**Comment by Rsl1122** [comment]
Cause is the same as #8
Further replies concerning this issue replied there.
