### ISSUE TITLE
CompletionException: com.djrapitops.plan.api.exceptions.database.DBOpException: CleanTransaction failed: null

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#937]
Plan 4.7.0 DEV2
Paper dev 548 (Spigot 1.13.2)

Restarted my server after updating to 4.7.0 DEV2 and noticed this error.

```
[09:01:03] [Plan MySQLDB-transaction-thread-0/ERROR]: [Plan] Error was caught by com.djrapitops.plan.db.MySQLDB
java.util.concurrent.CompletionException: com.djrapitops.plan.api.exceptions.database.DBOpException: CleanTransaction failed: null, Transaction was rolled back.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.djrapitops.plan.api.exceptions.database.DBOpException: CleanTransaction failed: null, Transaction was rolled back.
	at com.djrapitops.plan.db.access.transactions.Transaction.manageFailure(Transaction.java:85) ~[?:?]
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:70) ~[?:?]
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:214) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
	... 3 more
Caused by: java.lang.NullPointerException
	at com.djrapitops.plan.db.access.QueryStatement.executeQuery(QueryStatement.java:57) ~[?:?]
	at com.djrapitops.plan.db.access.transactions.Transaction.query(Transaction.java:115) ~[?:?]
	at com.djrapitops.plan.db.access.transactions.commands.RemovePlayerTransaction.performOperations(RemovePlayerTransaction.java:48) ~[?:?]
	at com.djrapitops.plan.db.access.transactions.Transaction.executeOther(Transaction.java:144) ~[?:?]
	at com.djrapitops.plan.db.access.transactions.init.CleanTransaction.cleanOldPlayers(CleanTransaction.java:88) ~[?:?]
	at com.djrapitops.plan.db.access.transactions.init.CleanTransaction.performOperations(CleanTransaction.java:76) ~[?:?]
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:66) ~[?:?]
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:214) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
	at com.djrapitops.plan.db.SQLDB.executeTransaction(SQLDB.java:210) ~[?:?]
	at com.djrapitops.plan.db.tasks.DBCleanTask.run(DBCleanTask.java:73) ~[?:?]
	at com.djrapitops.plugin.task.bukkit.BukkitRunnableFactory$1.run(BukkitRunnableFactory.java:55) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-548]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-548]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-548]
	... 3 more
```

**Comment by Rsl1122** [comment]
This was a pretty significant bug, nice that it was found :)

**Comment by Rsl1122** [comment]
[Plan-4.7.0-b2#937.zip](https://github.com/Rsl1122/Plan-PlayerAnalytics/files/2916099/Plan-4.7.0-b2.937.zip)

Here is a version with a fix

**Comment by mibby** [comment]
Thanks for the quick fix! Seems to have done the trick. :)
