### ISSUE TITLE
Bug with Jobs

### ISSUE THREAD

**Issue by Pyario** [Rsl1122/Plan-PlayerAnalytics#952]
### Describe the bug
Bug with "Jobs.enable = true"

### Server information
PaperSpigot Latest (1.13.2)
Plan | Player Analytics 4.7.1

### Exceptions & Other Logs
[11:58:29 ERROR]: [Plan] A PluginData-source caused an exception: Jobs, you can disable the integration under 'Plugins.Jobs.Enabled'
[11:58:29 WARN]: [Plan] Error was caught by com.djrapitops.plan.utilities.html.structure.AnalysisPluginsTabContentCreator
java.lang.NullPointerException: null
        at com.djrapitops.pluginbridge.plan.jobs.JobsData.getServerData(JobsData.java:68) ~[?:?]
        at com.djrapitops.plan.utilities.html.structure.AnalysisPluginsTabContentCreator.lambda$analyzeAdditionalPluginData$0(AnalysisPluginsTabContentCreator.java:148) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_201]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_201]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_201]
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[?:1.8.0_201]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_201]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_201]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_201]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_201]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_201]

### Additional information
I used the latest Version on Jobs. :)

**Comment by Rsl1122** [comment]
Please follow https://github.com/Zrips/Jobs/issues/377 for resolution to this issue.

Jobs changed how their database manager is initialized and that causes this bug.

**Comment by Pyario** [comment]
okay. :)

Thanks
